import { EgyptianMedication } from './types';

export const DWAPRICES_EGYPTIAN_MEDS: EgyptianMedication[] = [
  // =========================================================================
  // 1. Limitless Line (مجموعة ليميتلس المتقدمة - EVA Pharma)
  // =========================================================================
  {
    id: 'limitless_woman_max',
    tradeName: 'ليمتلس وومان ماكس (Limitless Woman Max)',
    tradeNameEn: 'Limitless Woman Max Complete Multivitamin & Mineral Formula (EVA Pharma)',
    scientificName: '26 فيتامين ومعدن أساسي + بيوتين + زنك + حديد + مضادات أكسدة للنساء',
    category: 'supplements',
    categoryAr: 'الفيتامين المتكامل لصحة المرأة، النشاط والحيوية، ونضارة البشرة وتقوية الشعر',
    categoryIcon: '👩',
    defaultTiming: 'قرص واحد يومياً بعد وجبة الإفطار أو الغداء مباشرة مع كوب ماء',
    dosageForm: 'أقراص مغلفة',
    commonDoses: ['1 قرص يومياً'],
    clinicalNotes: 'يغطي 100% من الاحتياج اليومي للحديد والزنك وحمض الفوليك وفيتامينات B المركبة وفيتامين D3، مصمم خصيصاً لدعم الطاقة اليومية وتوازن الهرمونات ونمو الشعر والأظافر.',
    searchTokens: ['ليمتلس وومان', 'limitless woman max', 'فيتامين حريمي', 'ليمتلس ستات', 'شعر وبشرة', 'مالتي فيتامين نسائي']
  },
  {
    id: 'limitless_man_max',
    tradeName: 'ليمتلس مان ماكس (Limitless Man Max)',
    tradeNameEn: 'Limitless Man Max Advanced Multivitamin & Energy Formula (EVA Pharma)',
    scientificName: '27 فيتامين ومعدن + ليكوبين + زنك مكثف + مغنيسيوم + مضادات أكسدة للرجال',
    category: 'supplements',
    categoryAr: 'الفيتامين المتكامل للرجال لزيادة طاقة العضلات، دعم البروستاتا، والمناعة والنشاط البدني',
    categoryIcon: '👨',
    defaultTiming: 'قرص واحد يومياً بعد وجبة الإفطار أو الغداء',
    dosageForm: 'أقراص مغلفة',
    commonDoses: ['1 قرص يومياً'],
    clinicalNotes: 'مدعم بمادة الليكوبين (Lycopene) والزنك لحماية البروستاتا، مع تركيزات عالية من المغنيسيوم وفيتامينات B لزيادة الأداء العضلي والقدرة الذهنية والبدنية للرجال.',
    searchTokens: ['ليمتلس مان', 'limitless man max', 'فيتامين رجالي', 'ليمتلس رجال', 'بروستاتا وطاقة', 'مالتي فيتامين للرجال']
  },
  {
    id: 'limitless_b_plus_film',
    tradeName: 'ليمتلس فيتامين ب بلس فيلم سريع الذوبان (Limitless Vitamin B Plus Oral Film)',
    tradeNameEn: 'Limitless Vitamin B Plus Fast-Dissolving Oral Strips (B1, B6, B12 Methylcobalamin)',
    scientificName: 'فيتامين ب1 + ب6 + ب12 ميثيل كوبالامين النشط على هيئة شرائح فموية سريعة الامتصاص',
    category: 'supplements',
    categoryAr: 'الفيلم الفموي الأسرع امتصاصاً لعلاج تنميل الأعصاب وإرهاق الجسد دون المرور بالجهاز الهضمي',
    categoryIcon: '🧠',
    defaultTiming: 'شريحة واحدة توضع على اللسان صباحاً وتذوب تلقائياً خلال ثوانٍ بدون ماء',
    dosageForm: 'أفلام فموية سريعة الذوبان (Oral Dissolving Strips)',
    commonDoses: ['1 فيلم فموي يومياً'],
    clinicalNotes: 'يمتص فورياً عبر الأوعية الدموية تحت اللسان بطريقة Sublingual / Buccal، مما يمنح فاعلية تماثل الحقن في رفع مستويات B12 وعلاج التهابات الأعصاب الطرفية لدى مرضى السكري.',
    searchTokens: ['ليمتلس ب بلس', 'limitless b plus', 'فيلم ب12', 'شرائح ب12', 'تنميل اعصاب', 'ميثيل كوبالامين']
  },
  {
    id: 'limitless_milga_max',
    tradeName: 'ليمتلس ميلجا ماكس (Limitless Milga Max)',
    tradeNameEn: 'Limitless Milga Max (Benfotiamine + Pyridoxine + Methylcobalamin + Magnesium)',
    scientificName: 'بينفوتيامين 300 مجم (B1 الذائب في الدهون) + B6 + B12 ميثيل كوبالامين + مغنيسيوم',
    category: 'supplements',
    categoryAr: 'تقوية الأعصاب الطرفية الشديدة، التخلص من آلام الفقرات والظهر، ودعم نشاط العضلات',
    categoryIcon: '🧠',
    defaultTiming: 'قرص واحد يومياً بعد وجبة الغداء مع كوب ماء',
    dosageForm: 'أقراص مغلفة',
    commonDoses: ['1 قرص يومياً'],
    clinicalNotes: 'يحتوي على البينفوتيامين (Benfotiamine) وهو الصورة الذائبة في الدهون من B1 التي تخترق أغشية الأعصاب بفاعلية تزيد 5 أضعاف عن التيامين العادي لعلاج التهاب الأعصاب السكري.',
    searchTokens: ['ميلجا ماكس', 'limitless milga max', 'بينفوتيامين', 'تنميل رجليين', 'اعصاب سكري', 'التهاب اعصاب']
  },
  {
    id: 'limitless_chromax_cut',
    tradeName: 'ليمتلس كروماكس كت فوار التخسيس (Limitless Chromax Cut)',
    tradeNameEn: 'Limitless Chromax Cut Sachet (Glucomannan + Inulin + Chromium Picolinate + Green Coffee)',
    scientificName: 'ألياف الجلوكومانان + إنولين + كروميوم بيكولينات + مستخلص القهوة الخضراء',
    category: 'weight_loss',
    categoryAr: 'أكياس الشبع الفوري وإغلاق الشهية وحرق الدهون وتثبيت سكر الدم قبل الوجبات',
    categoryIcon: '⚖️',
    defaultTiming: 'كيس يذاب في كوب ماء كبير قبل الوجبة بـ 30 دقيقة ويُتبع بكوب ماء آخر إلزامياً',
    dosageForm: 'أكياس بودرة فوارة بأسلوب الألياف الهلامية',
    commonDoses: ['كيس 2-3 مرات يومياً قبل الوجبات الكبيرة'],
    clinicalNotes: 'يتمدد الجلوكومانان والإنولين في المعدة ليكونا جيل هلامي يملأ المعدة ويرسل إشارات الشبع، بينما يضبط الكروميوم والقهوة الخضراء استجابة الأنسولين وحرق الدهون.',
    searchTokens: ['كروماكس كت', 'limitless chromax cut', 'ليمتلس تخسيس', 'افياف شبع', 'جلوكومانان فوار', 'سد شهية']
  },

  // =========================================================================
  // 2. Classical Egyptian Multivitamins & Tonics (الفيتامينات والمقويات المصرية الشهيرة)
  // =========================================================================
  {
    id: 'royal_vit_g_caps',
    tradeName: 'رويال فيت جي كبسول (Royal Vit G)',
    tradeNameEn: 'Royal Vit G Energy & Vitality Capsules (Ginseng + Royal Jelly + Dimethylaminoethanol DMAE)',
    scientificName: 'خلاصة الجنسنج + غذاء ملكات النحل + دي إم أي إي (DMAE) + 20 فيتامين ومعدن',
    category: 'supplements',
    categoryAr: 'المقوي العام الكلاسيكي لزيادة الكفاءة البدنية والعقلية، تقليل الإجهاد، وزيادة التركيز',
    categoryIcon: '👑',
    defaultTiming: 'كبسولة واحدة يومياً بعد وجبة الإفطار مباشرة مع كوب ماء',
    dosageForm: 'كبسولات جيلاتينية رخوة',
    commonDoses: ['1 كبسولة يومياً صباحاً'],
    clinicalNotes: 'التركيبة الذهبية التي تجمع بين الجنسنج وغذاء الملكات ومركب DMAE المحفز للنواقل العصبية بالدماغ لزيادة الحيوية والنشاط اليومي ومكافحة الخمول والإجهاد البدني.',
    searchTokens: ['رويال فيت جي', 'royal vit g', 'جنسنج وغذاء ملكات', 'مقوي عام', 'ارهاق وخمول', 'زيادة نشاط']
  },
  {
    id: 'kerovit_softgels',
    tradeName: 'كيروفيت 46 عنصر جيلاتيني (Kerovit Softgels)',
    tradeNameEn: 'Kerovit Comprehensive Multivitamin & Mineral 46 Ingredients Complex (Amoun)',
    scientificName: '46 عنصر حيوياً: فيتامينات، معادن، أحماض أمينية، كوإنزيم Q10، غذاء ملكات، وأوميجا 3',
    category: 'supplements',
    categoryAr: 'مجمّع الـ 46 عنصراً المغذي الشامل للمناعة والذاكرة والنشاط وحماية الخلايا',
    categoryIcon: '💊',
    defaultTiming: 'كبسولة واحدة يومياً بعد وجبة الغداء مع كوب ماء',
    dosageForm: 'كبسولات جيلاتينية رخوة حمراء داكنة',
    commonDoses: ['1 كبسولة يومياً'],
    clinicalNotes: 'يحتوي على أكبر تنوع إكلينيكي للعناصر في كبسولة واحدة بمصر (46 عنصر) بما فيها الكوإنزيم Q10، الأوميجا 3، ومضادات الأكسدة للوقاية من نقص المغذيات والإجهاد.',
    searchTokens: ['كيروفيت', 'kerovit', 'كيروفيت 46', 'اربعين عنصر', 'امون كيروفيت', 'مالتي فيتامين شامل']
  },
  {
    id: 'octatron_antioxidant',
    tradeName: 'أكتاترون مضاد الأكسدة والشعر (Octatron Capsules)',
    tradeNameEn: 'Octatron Antioxidant & Chelated Minerals Complex (Nerca Pharma)',
    scientificName: 'سيلينيوم + زنك مخلبي + بيوتين + فيتامين A, C, E + فلافونويد حيوية + موليبدنوم',
    category: 'supplements',
    categoryAr: 'مضاد الأكسدة المخلبي لحماية الخلايا، علاج تساقط الشعر، وتحسين كفاءة الحيوانات المنوية',
    categoryIcon: '🛡️',
    defaultTiming: 'كبسولة واحدة يومياً بعد وجبة الإفطار أو الغداء مع ماء',
    dosageForm: 'كبسولات صلبة',
    commonDoses: ['1 كبسولة يومياً بعد الأكل'],
    clinicalNotes: 'يتميز بالمعادن المخلبية المرتبطة بأحماض أمينية لضمان الامتصاص الفائق لحماية البصيلات والحيوانات المنوية من الأكسدة وتلف الشواريد الحرة.',
    searchTokens: ['اكتاترون', 'octatron', 'مضاد اكسدة اكتاترون', 'سيلينيوم زنك', 'تساقط شعر زنك']
  },
  {
    id: 'immulant_echinacea_caps',
    tradeName: 'إيمولانت كبسول وشراب (Immulant Capsules & Immulant N Syrup)',
    tradeNameEn: 'Immulant Pure Echinacea Extract 125mg Capsules & Syrup (MEPACO)',
    scientificName: 'المستخلص الجاف لنبات الإخيناسيا / حبة البركة (Echinacea Dry Extract)',
    category: 'supplements',
    categoryAr: 'المحفز المناعي الطبيعي للوقاية من نزلات البرد وتكرار العدوى وحماية الجهاز التنفسي',
    categoryIcon: '🌿',
    defaultTiming: 'كبسولة 3 مرات يومياً للأبالغين / 5 مل 3 مرات يومياً للأطفال لمدة أسبوعين',
    dosageForm: 'كبسولات / شراب 120 مل',
    commonDoses: ['1-2 كبسولة 3 مرات يومياً عند نزلات البرد'],
    clinicalNotes: 'ينشط كرات الدم البيضاء والخلايا البلعمية (Phagocytes) لمكافحة العدوى الفيروسية والبكتيرية التنفسية، يفضل استخدامه كورسات قصيرة (2-4 أسابيع).',
    searchTokens: ['ايمولانت', 'immulant', 'اخيناسيا', 'echinacea', 'شراب ايمولانت', 'مناعة برد اطفال']
  },
  {
    id: 'feroglobin_b12_iron',
    tradeName: 'فيروجلوبين كبسول وشراب (Feroglobin B12 - Vitabiotics / Egyptian Market)',
    tradeNameEn: 'Feroglobin B12 Gentle Iron, Zinc, Copper, Folic Acid & B Complex (Vitabiotics)',
    scientificName: 'حديد مخلبي لطيف + زنك + نحاس + حمض الفوليك + فيتامين B6 & B12',
    category: 'supplements',
    categoryAr: 'كبسولات ممتدة المفعول لعلاج أنيميا نقص الحديد بدون آلام المعدة أو الإمساك',
    categoryIcon: '🩸',
    defaultTiming: 'كبسولة واحدة يومياً بعد وجبة الغداء مع كوب ماء أو عصير برتقال',
    dosageForm: 'كبسولات بطيئة التحرر (Slow Release) / شراب للأطفال',
    commonDoses: ['1 كبسولة يومياً'],
    clinicalNotes: 'تفرز كبسولات فيروجلوبين الكريات الدقيقة تدريجياً داخل الأمعاء الدقيقة لمنع تلامس الحديد المباشر مع جدار المعدة، مما يمنع الغثيان والإمساك تماماً.',
    searchTokens: ['فيروجلوبين', 'feroglobin', 'حديد فيروجلوبين', 'انيميا بدون امساك', 'حمض الفوليك حديد']
  },
  {
    id: 'carnivita_forte_30',
    tradeName: 'كارنيفيتا فورت وكارنيفيتا أدفانس (Carnivita Forte / Carnivita Advance)',
    tradeNameEn: 'Carnivita Forte (L-Carnitine Tartrate 1000mg + Zinc 50mg - Eva Pharma)',
    scientificName: 'إل-كارنيتين تارترات 1000 مجم + زنك عنصري 50 مجم (L-Carnitine + Zinc)',
    category: 'supplements',
    categoryAr: 'حرق الدهون وتوليد طاقة العضلات، وتحسين حركة وعدد الحيوانات المنوية وزيادة الخصوبة',
    categoryIcon: '🏋️',
    defaultTiming: 'قرص واحد 1-2 مرة يومياً قبل التمرين أو بعد الوجبات',
    dosageForm: 'أقراص مغلفة / أقراص للمضغ',
    commonDoses: ['1000 مجم إل-كارنيتين مرتين يومياً'],
    clinicalNotes: 'ينقل الأحماض الدهنية طويلة السلسلة لداخل الميتوكوندريا ليتم حرقها وإنتاج جزيئات طاقة ATP، مما يزيد تحريك الدهون العالقة ويرفع جودة وحركة الحيوانات المنوية.',
    searchTokens: ['كارنيفيتا', 'carnivita', 'كارنيفيتا فورت', 'كارنيتين زنك', 'حركة الحيوانات المنوية', 'حرق دهون']
  },

  // =========================================================================
  // Page 1: (id=5) أدوية فيتامينات كاملة - DWAPRICES Vitamins Page Complete List
  // =========================================================================
  {
    id: 'milga_advance_30_tab',
    tradeName: 'ميلجا وميلجا أدفانس (Milga & Milga Advance Tablets - Eva Pharma)',
    tradeNameEn: 'Milga / Milga Advance (Benfotiamine 300mg + Pyridoxine 100mg + Cyanocobalamin 250mcg)',
    scientificName: 'بينفوتيامين (فيتامين B1 الذائب في الدهون) + ب6 + ب12',
    category: 'supplements',
    categoryAr: 'علاج التهابات الأعصاب الطرفية، ألم الظهر والفقرات، وتنميل اليدين والقدمين',
    categoryIcon: '⚡',
    defaultTiming: 'قرص واحد 1-3 مرات يومياً بعد الوجبات مع كوب ماء',
    dosageForm: 'أقراص مغلفة',
    commonDoses: ['1 قرص 1-2 مرة يومياً'],
    clinicalNotes: 'الدواء المصري الأكثر مبيعاً لتقوية الأعصاب. البينفوتيامين يمتص بسرعة فائقة ويدخل الخلايا العصبية لتقوية التوصيل العصبي وتقليل ألم الأعصاب لدى مرضى السكري.',
    searchTokens: ['ميلجا', 'milga', 'ميلجا ادفانس', 'milga advance', 'تنميل اعصاب', 'اعصاب سكري', 'وجع ظهر']
  },
  {
    id: 'neurovit_30_tab',
    tradeName: 'نيوروفيت أقراص وأمبولات (Neurovit Tablets & Ampoules - Amoun)',
    tradeNameEn: 'Neurovit Tablets & Injections (Vitamin B1 + Vitamin B6 + Vitamin B12)',
    scientificName: 'ثيامين (B1) 250 مجم + بيريدوكسين (B6) 100 مجم + سيانوكوبالامين (B12) 250 مكجم',
    category: 'supplements',
    categoryAr: 'تقوية الأعصاب، علاج الأنيميا الناجمة عن نقص ب12، وتنشيط الذاكرة والأداء البدني',
    categoryIcon: '🧠',
    defaultTiming: 'قرص واحد 1-3 مرات يومياً بعد الأكل / أو أمبولة عضل يوم بعد يوم',
    dosageForm: 'أقراص مغلفة / أمبولات للحقن العضلي',
    commonDoses: ['1 قرص 2-3 مرات يومياً'],
    clinicalNotes: 'تركيبة فيتامين ب المركب الكلاسيكية الشاملة لتجديد الغلاف الماياليني للأعصاب ومنع الأنيميا خبيثة الشكل.',
    searchTokens: ['نيوروفيت', 'neurovit', 'حقن نيوروفيت', 'اقراص نيوروفيت', 'فيتامين ب المركب', 'تنميل']
  },
  {
    id: 'thiotacid_600_compound',
    tradeName: 'ثيوتاسيد 300 و600 ومركب (Thiotacid 300mg / 600mg / Thiotacid Compound)',
    tradeNameEn: 'Thiotacid Compound (Alpha Lipoic Acid 600mg + Benfotiamine + Vit B12 - Eva)',
    scientificName: 'حمض الألفا ليبويك (Alpha Lipoic Acid) + بينفوتيامين + فيتامين B12',
    category: 'supplements',
    categoryAr: 'مضاد الأكسدة القوي لعلاج التهاب الأعصاب السكري، الاعتلال العصبي، والاعتلال البصري',
    categoryIcon: '🛡️',
    defaultTiming: 'قرص واحد 600 مجم يومياً على معدة فارغة قبل الأكل بـ 30 دقيقة أو بعده بساعتين',
    dosageForm: 'أقراص مغلفة',
    commonDoses: ['600 مجم يومياً قبل الأكل'],
    clinicalNotes: 'حمض الألفا ليبويك يحمي الألياف العصبية الدقيقة من التلف الأكسدي الناتج عن ارتفاع سكر الدم، ويحسن تدفق الدم المصغر للأعصاب.',
    searchTokens: ['ثيوتاسيد', 'thiotacid', 'ثيوتاسيد مركب', 'ثيوتاسيد 600', 'الفا ليبويك', 'اعصاب سكري']
  },
  {
    id: 'c_retard_500_caps',
    tradeName: 'سي ريتارد 500 مجم كبسول (C-Retard 500mg SR Capsules - Hikma)',
    tradeNameEn: 'C-Retard 500mg Sustained Release Vitamin C Capsules',
    scientificName: 'حمض الأسكوربيك / فيتامين ج (Ascorbic Acid) 500 مجم ممتد المفعول',
    category: 'supplements',
    categoryAr: 'تقوية المناعة، محاربة البرد والإنفلونزا، تحفيز إنتاج الكولاجين، وزيادة امتصاص الحديد',
    categoryIcon: '🍊',
    defaultTiming: 'كبسولة واحدة 1-2 مرة يومياً بعد الأكل مع ماء',
    dosageForm: 'كبسولات ممتدة المفعول (Sustained Release)',
    commonDoses: ['500-1000 مجم يومياً'],
    clinicalNotes: 'كبسولة ذات حبيبات دقيقة تطلق فيتامين C ببطء على مدار 12 ساعة لتوفير مستويات ثابتة في الدم دون إجهاد الكلى أو حرقة المعدة.',
    searchTokens: ['سي ريتارد', 'c retard', 'فيتامين سي 500', 'سي ريتارد كبسول', 'مناعة برد']
  },
  {
    id: 'vit_e_400_e_viton',
    tradeName: 'فيتامين هـ وفيتون 400 و1000 مجم (Vitamin E 400mg & 1000mg / E-Viton)',
    tradeNameEn: 'Vitamin E 400mg / 1000mg Pure d-Alpha Tocopherol Gel Capsules (Kahira / Pharco)',
    scientificName: 'فيتامين هـ (d-Alpha Tocopherol) 400 مجم / 1000 مجم',
    category: 'supplements',
    categoryAr: 'مضاد الأكسدة الذائب في الدهون لنضارة البشرة، دعم الخصوبة، وحماية أغشية الخلايا',
    categoryIcon: '✨',
    defaultTiming: 'كبسولة واحدة يومياً بعد وجبة الغداء مباشرة (وجبة تحتوي على دهون صحية)',
    dosageForm: 'كبسولات جيلاتينية رخوة',
    commonDoses: ['400 مجم يومياً'],
    clinicalNotes: 'يحمي الأحماض الدهنية غير المشبعة في أغشية الخلايا من الأكسدة، يحسن جودة الحيوانات المنوية، ويمنح نضارة فائقة للجلد.',
    searchTokens: ['فيتامين هـ', 'فيتامين e', 'e viton', 'اي فيتون', 'نضارة بشرة', 'خصوبة رجال']
  },
  {
    id: 'zincotron_chelated',
    tradeName: 'زينكوترون وأوكتازينك (Zincotron & Octazinc Amino Acid Chelated Zinc)',
    tradeNameEn: 'Zincotron Capsules (Chelated Zinc 11mg + Vitamin C + Citrus Bioflavonoids)',
    scientificName: 'زنك مخلبي مع الأحماض الأمينية + فيتامين C + فلافونويد حيوية',
    category: 'supplements',
    categoryAr: 'تقوية المناعة، الوقاية من تساقط الشعر، تسريع التئام الجروح، وعلاج حب الشباب',
    categoryIcon: '🛡️',
    defaultTiming: 'كبسولة واحدة يومياً بعد وجبة الإفطار أو الغداء مع كوب ماء',
    dosageForm: 'كبسولات صلبة',
    commonDoses: ['1 كبسولة يومياً'],
    clinicalNotes: 'زنك مخلبي عالي الامتصاص لا يسبب غثيان أو اضطراب في المعدة مقارنة بسلفات الزنك العادية.',
    searchTokens: ['زينكوترون', 'zincotron', 'اوكتازينك', 'زنك مخلبي', 'تساقط شعر زنك', 'مناعة زنك']
  },
  {
    id: 'genuphil_advance_5',
    tradeName: 'جينوفيل وجينوفيل أدفانس (Genuphil & Genuphil Advance Syrup/Tablets - Eva)',
    tradeNameEn: 'Genuphil Advance Sachet / Tablets (Glucosamine 1500mg + Chondroitin + MSM + Collagen Type II)',
    scientificName: 'جلوكوزامين 1500 مجم + شوندرميتين + إم إس إم (MSM) + كولاجين النوع الثاني + الهيالورونيك',
    category: 'joints_bones',
    categoryAr: 'العلاج المركب الخماسي الأكثر مبيعاً لعلاج خشونة الركبتين وتآكل الغضاريف والمفاصل',
    categoryIcon: '🦴',
    defaultTiming: 'قرص واحد 3 مرات يومياً بعد الأكل / أو كيس واحد فوار يومياً يذاب في كوب ماء',
    dosageForm: 'أقراص / أكياس فوارة / شراب',
    commonDoses: ['كيس واحد أو 3 أقراص يومياً'],
    clinicalNotes: 'يبني الغضاريف التالفة، يقلل احتكاك المفاصل، ويوفر الإم إس إم التسكين الطبيعي للآلام المزمنة.',
    searchTokens: ['جينوفيل', 'genuphil', 'جينوفيل ادفانس', 'خشونة ركبة', 'تاكل غضاريف', 'مفاصل ركبة']
  },
  {
    id: 'dorofen_capsules_dwa',
    tradeName: 'دوروفين كبسول (Dorofen Capsules - Lipanthyl/Egyptian Market)',
    tradeNameEn: 'Dorofen Capsules (Glucosamine Sulfate 500mg + Ginkgo Biloba Leaf Extract 50mg)',
    scientificName: 'جلوكوزامين سلفات 500 مجم + مستخلص أوراق الجينكو بيلوبا 50 مجم',
    category: 'joints_bones',
    categoryAr: 'علاج خشونة المفاصل والرقبة مع تنشيط الدورة الدموية وتغذية غضاريف الساقين',
    categoryIcon: '🦴',
    defaultTiming: 'كبسولة واحدة 3 مرات يومياً بعد الوجبات لمدة 3-4 أسابيع ثم كبسولة 1-2 مرة للصيانة',
    dosageForm: 'كبسولات صلبة',
    commonDoses: ['1 كبسولة 3 مرات يومياً'],
    clinicalNotes: 'الدمج الذكي بين الجلوكوزامين الباني للغضاريف والجينكو بيلوبا المجمعة للدورة الدموية يضمن وصول المغذيات لعمق المفاصل وتخفيف خشونة الرقبة.',
    searchTokens: ['دوروفين', 'dorofen', 'جينكو جيلكوزامين', 'خشونة مفاصل ورقبة', 'غضاريف']
  },
  {
    id: 'depovit_b12_amp_dwa',
    tradeName: 'ديبوفيت ب12 أمبول (Depovit B12 Depot - Amoun)',
    tradeNameEn: 'Depovit B12 Ampoules (Hydroxocobalamin 1000mcg Depot Injection)',
    scientificName: 'هيدروكسو كوبالامين (Hydroxocobalamin) 1000 ميكروجرام ممتد المفعول',
    category: 'supplements',
    categoryAr: 'حقن ب12 الشهرية الممتدة لعلاج الأنيميا الحادة وتنميل الأعصاب وإرهاق الجسد',
    categoryIcon: '💉',
    defaultTiming: 'حقنة واحدة عضل أسبوعياً أو كل شهر حسَب شدة النقص والتعليمات الطبية',
    dosageForm: 'أمبولات زجاجية للحقن العضلي',
    commonDoses: ['1 أمبولة عضل أسبوعياً أو شهرياً'],
    clinicalNotes: 'صورة الهيدروكسوكوبالامين ترتبط ببروتينات الدم وتفرز ببطء شديد، مما يمنح مفعولاً ممتداً في الجسم لعدة أسابيع مقارنة بالسيانوكوبالامين.',
    searchTokens: ['ديبوفيت', 'depovit b12', 'حقنة ديبوفيت', 'حقن ب12 شهرية', 'تنميل وانيميا']
  },
  {
    id: 'tot_hema_ampoules',
    tradeName: 'توت هيما أمبولات فموية (Tot\'Hema Oral Ampoules - Innotech)',
    tradeNameEn: 'Tot\'Hema Drinkable Ampoules (Elemental Iron 50mg + Manganese 1.33mg + Copper 0.7mg)',
    scientificName: 'حديد جلوكونات ثنائي 50 مجم + منجنيز + نحاس أمبولات للشرب',
    category: 'supplements',
    categoryAr: 'أمبولات الحديد الفموية سريعة الارتفاع بالهيموجلوبين لعلاج الأنيميا الشديدة للحوامل والأطفال',
    categoryIcon: '🩸',
    defaultTiming: 'أمبولة واحدة تفصم وتذاب في كوب ماء أو عصير برتقال وتشرَب قبل الأكل أو مع الوجبة',
    dosageForm: 'أمبولات زجاجية للشرب الفموي',
    commonDoses: ['1-2 أمبولة فموية يومياً'],
    clinicalNotes: 'تركيبة الحديد السائل المدعمة بالنحاس والمنجنيز تضمن أعلى امتصاص معوي مع رفع الهيموجلوبين بفترة قياسية مقارنة بالأقراص.',
    searchTokens: ['توت هيما', 'tot hema', 'امبولات توت هيما', 'حديد شرب', 'انيميا حوامل', 'رفع هيموجلوبين']
  },
  {
    id: 'haemojet_haemofer',
    tradeName: 'هيموجيت وهيموفر بوليمالتوز (Haemojet & Haemofer Iron Polymaltose)',
    tradeNameEn: 'Haemojet / Haemofer (Iron III Hydroxide Polymaltose Complex 100mg)',
    scientificName: 'مركب هيدروكسيد الحديد الثلاثي مع البوليمالتوز 100 مجم (Iron Polymaltose)',
    category: 'supplements',
    categoryAr: 'الحديد غير المتهيج للمعدة والأمعاء لعلاج فقر الدم بدون إمساك أو تغير لون الأسنان',
    categoryIcon: '🩸',
    defaultTiming: 'قرص واحد يومياً أثناء أو بعد وجبة الغداء مباشرة',
    dosageForm: 'أقراص للمضغ / شراب / نقط',
    commonDoses: ['1 قرص يومياً مع الطعام'],
    clinicalNotes: 'مركب البوليمالتوز يغلف الحديد برابطة غير تأينيه، فلا يتفاعل مع الأطعمة في المعدة ولا يسبب إمساكاً أو آلاماً معوية.',
    searchTokens: ['هيموجيت', 'haemojet', 'هيموفر', 'حديد بوليمالتوز', 'انيميا بدون امساك']
  },
  {
    id: 'ginkgovit_260mg',
    tradeName: 'جينكوفيت وجينكو بيلوبا (Ginkgovit / Ginkgo Biloba 260mg)',
    tradeNameEn: 'Ginkgo Biloba Extract 260mg (Standardized Flavone Glycosides & Terpene Lactones)',
    scientificName: 'مستخلص أوراق الجينكو بيلوبا المعياري 260 مجم',
    category: 'supplements',
    categoryAr: 'تنشيط التروية الدموية للمخ والأطراف، تقوية الذاكرة، وعلاج طنين الأذن والدوخة',
    categoryIcon: '🌿',
    defaultTiming: 'كبسولة واحدة يومياً بعد وجبة الإفطار مع كوب ماء',
    dosageForm: 'كبسولات صلبة',
    commonDoses: ['1 كبسولة يومياً'],
    clinicalNotes: 'يوسع الشعيرات الدموية الدقيقة بالدماغ والأذن الداخلية والأطراف، مما يزيد تدفق الأكسجين ويحارب الزهايمر وطنين الأذن.',
    searchTokens: ['جينكوفيت', 'ginkgovit', 'جينكو بيلوبا', 'طنين الأذن', 'دوخة وتركيز', 'تروية دماغية']
  },
  {
    id: 'vitazinc_caps_dwa',
    tradeName: 'فيتازينك كبسول (Vitazinc Capsules - EVA Pharma)',
    tradeNameEn: 'Vitazinc Capsules (Zinc Sulfate 50mg + Vitamin A 2500IU + Vitamin E 15mg)',
    scientificName: 'زنك سلفات 50 مجم (11 مجم زنك عنصري) + فيتامين أ + فيتامين هـ',
    category: 'supplements',
    categoryAr: 'التركيبة الثلاثية الكلاسيكية لعلاج حب الشباب، نقاء البشرة، وتكثيف البصيلات',
    categoryIcon: '✨',
    defaultTiming: 'كبسولة واحدة يومياً بعد وجبة الغداء مع كوب ماء',
    dosageForm: 'كبسولات صلبة',
    commonDoses: ['1 كبسولة يومياً'],
    clinicalNotes: 'يجمع الزنك المقلل لإفراز الدهون مع فيتامين A المجدد لخلايا الجلد وفيتامين E المضاد للأكسدة لعلاج النمش وحب الشباب.',
    searchTokens: ['فيتازينك', 'vitazinc', 'زنك وحب شباب', 'زنك وبشرة', 'كبسول فيتازينك']
  },
  {
    id: 'calcibronat_eff',
    tradeName: 'كالسيبرونات فوار (Calcibronat Effervescent - Novartis)',
    tradeNameEn: 'Calcibronat Effervescent Tablets (Calcium Bromo-Galactogluconate 2g)',
    scientificName: 'برومو-جالاكتوجلوكونات الكالسيوم 2 جرام',
    category: 'joints_bones',
    categoryAr: 'الكالسيوم الفوار المهدئ للأعصاب، علاج التوتر العصبي، وتقوية العظام والأعصاب',
    categoryIcon: '🦴',
    defaultTiming: 'قرص فوار واحد يذاب في نصف كوب ماء يومياً مساءً قبل النوم',
    dosageForm: 'أقراص فوارة',
    commonDoses: ['1 قرص فوار يومياً مساءً'],
    clinicalNotes: 'يوفر أيونات الكالسيوم مع أثر البروميد المهدئ خفيفاً للجهاز العصبي، فيساعد على الهدوء والاسترخاء مع تغذية الهيكل العظمي.',
    searchTokens: ['كالسيبرونات', 'calcibronat', 'فوار كالسيوم مهدئ', 'توتر واعصاب', 'كالسيوم نوفرتس']
  },
  {
    id: 'caltrate_plus_600',
    tradeName: 'كالترات وكالترات بلس (Caltrate 600 & Caltrate Plus - Pfizer)',
    tradeNameEn: 'Caltrate Plus (Calcium Carbonate 600mg + Vit D3 800IU + Minerals: Zinc, Copper, Manganese)',
    scientificName: 'كربونات الكالسيوم 600 مجم + فيتامين د3 800 وحدة + زنك + نحاس + منجنيز + بورون',
    category: 'joints_bones',
    categoryAr: 'الكالسيوم المعتمد عالمياً للوقاية وعلاج هشاشة العظام للنساء بعد انقطاع الطمث والحوامل',
    categoryIcon: '🦴',
    defaultTiming: 'قرص واحد 1-2 مرة يومياً بعد الأكل مباشرة مع كوب ماء',
    dosageForm: 'أقراص مغلفة',
    commonDoses: ['1 قرص 1-2 مرة يومياً'],
    clinicalNotes: 'مدعم بالمعادن الدقيقة (البورون، النحاس، المنجنيز) التي تدخل في تكوين مصفوفة العظام العضوية لتثبيت الكالسيوم داخل العظام بفاعلية.',
    searchTokens: ['كالترات', 'caltrate', 'كالترات بلس', 'هشاشة عظام', 'كالسيوم حوامل', 'كالسيوم وفيتامين د']
  },
  {
    id: 'v2_plus_softgels',
    tradeName: 'في تو بلس كبسول (V2 Plus Softgels - Pharco)',
    tradeNameEn: 'V2 Plus Energy Capsules (Ginseng Extract + Royal Jelly + Vitamins & Minerals)',
    scientificName: 'خلاصة الجنسنج + غذاء ملكات النحل + فيتامينات أ، د، هـ، ب المركب وزيت الأوميجا',
    category: 'supplements',
    categoryAr: 'كبسولات الحيوية اليومية، تجديد النشاط البدني، ومكافحة الإرهاق وضعف الذاكرة',
    categoryIcon: '🔋',
    defaultTiming: 'كبسولة واحدة يومياً بعد وجبة الإفطار مباشرة',
    dosageForm: 'كبسولات جيلاتينية رخوة',
    commonDoses: ['1 كبسولة يومياً صباحاً'],
    clinicalNotes: 'مجمّع فاركو الشهير لزيادة معدل التمثيل الغذائي والطاقة وتدعيم كرات الدم الحمراء والجهاز المناعي.',
    searchTokens: ['في تو بلس', 'v2 plus', 'جنسنج وغذاء ملكات فاركو', 'مقوي عام فاركو', 'كبسول نشاط']
  },
  {
    id: 'biotin_forte_5mg_dwa',
    tradeName: 'بيوتين فورت 5 مجم (Biotin Forte 5mg - Eva Pharma)',
    tradeNameEn: 'Biotin Forte 5mg High Potency Capsules',
    scientificName: 'بيوتين / فيتامين ب7 (Biotin) 5000 ميكروجرام (5 مجم)',
    category: 'supplements',
    categoryAr: 'الجرعة العلاجية المكثفة لوقف تساقط الشعر الشديد وتقوية الأظافر الهشة ومنع تقصفها',
    categoryIcon: '💅',
    defaultTiming: 'كبسولة واحدة يومياً بعد وجبة الغداء مع ماء',
    dosageForm: 'كبسولات صلبة',
    commonDoses: ['5000 مكجم (1 كبسولة) يومياً'],
    clinicalNotes: 'يحفز تصنيع بروتين الكيراتين في بصيلات الشعر وصفائح الأظافر، مما يزيد السمك واللمعان ويقلل التساقط.',
    searchTokens: ['بيوتين فورت', 'biotin forte', 'بيوتين 5 مجم', 'تساقط شعر بيوتين', 'تقصف الاظافر']
  },
  {
    id: 'folium_5mg_folic',
    tradeName: 'فوليوم وحمض الفوليك 5 مجم (Folium / Folic Acid 5mg)',
    tradeNameEn: 'Folic Acid 5mg Tablets (Essential Vitamin B9)',
    scientificName: 'حمض الفوليك (Folic Acid / Vitamin B9) 5 مجم',
    category: 'supplements',
    categoryAr: 'الوقاية المعتمدة من تشوهات الجنين العصبية، دعم الحوامل، وعلاج أنيميا نقص الفولات',
    categoryIcon: '🤰',
    defaultTiming: 'قرص واحد يومياً قبل أو بعد وجبة الإفطار',
    dosageForm: 'أقراص صلبة',
    commonDoses: ['1 قرص 5 مجم يومياً'],
    clinicalNotes: 'أساسي جداً للتناول قبل الحمل بـ 3 أشهر وطوال الثلث الأول لمنع العيوب الخلقية بالأنبوب العصبي للجنين (Neural Tube Defects).',
    searchTokens: ['فوليوم', 'folium', 'حمض الفوليك 5 مجم', 'فوليك اسيد حوامل', 'تشوهات الجنين']
  },
  {
    id: 'cebion_1000_eff',
    tradeName: 'سبيون 1000 فوار فيتامين سي (Cebion 1000mg Effervescent - Merck)',
    tradeNameEn: 'Cebion 1000mg Vitamin C Pure Effervescent Tablets',
    scientificName: 'حمض الأسكوربيك فيتامين C النقي 1000 مجم فوار',
    category: 'supplements',
    categoryAr: 'فوار فيتامين C الألماني النقي لزيادة المناعة السريعة ومحاربة الإنفلونزا والأكسدة',
    categoryIcon: '🍊',
    defaultTiming: 'قرص فوار واحد يذاب في نصف كوب ماء يومياً بعد الإفطار',
    dosageForm: 'أقراص فوارة بأسلوب سريع الانحلال',
    commonDoses: ['1000 مجم فوار يومياً'],
    clinicalNotes: 'انحلال وتأين سريع للفيتامين لضمان أفضل امتصاص معوي بدون ترك رواسب وتدعيم الخلايا البلعمية المناعية.',
    searchTokens: ['سبيون', 'cebion', 'فوار سبيون 1000', 'فوار فيتامين سي', 'مناعة برد']
  },
  {
    id: 'matrix_joyflex_collagen',
    tradeName: 'ماتريكس وجوي فليكس كولاجين (Matrix & Joyflex Hydrolyzed Collagen Sachet)',
    tradeNameEn: 'Matrix Sachet (Hydrolyzed Marine Collagen Peptides 10g + Vitamin C)',
    scientificName: 'ببتيدات الكولاجين البحري المتحلل 10 جم + فيتامين C + هيالورونيك أسيد',
    category: 'joints_bones',
    categoryAr: 'أكياس الكولاجين النقي لترميم غضاريف الركبتين وتحسين مرونة الجلد ونضارة البشرة',
    categoryIcon: '✨',
    defaultTiming: 'كيس واحد يومياً يذاب في نصف كوب ماء أو عصير صباحاً على معدة فارغة',
    dosageForm: 'أكياس بودرة',
    commonDoses: ['1 كيس يومياً صباحاً'],
    clinicalNotes: 'ببتيدات الكولاجين المتحللة منخفضة الوزن الجزيئي تمتص فورياً ونتجه لمصفوفة المفاصل والبشرة لبناء الأنسجة.',
    searchTokens: ['ماتريكس', 'matrix', 'جوي فليكس', 'joyflex', 'كولاجين أكياس', 'كولاجين بشرة ومفاصل']
  },
  {
    id: 'limitless_c_zinc',
    tradeName: 'ليميتلس سي زنك فوار (Limitless C-Zinc Effervescent - Eva Pharma)',
    tradeNameEn: 'Limitless C-Zinc (Vitamin C 1000mg + Zinc 15mg Fast Dissolving Effervescent)',
    scientificName: 'فيتامين C 1000 مجم + زنك عنصري 15 مجم فوار بنكهة البرتقال',
    category: 'supplements',
    categoryAr: 'الفوار المناعي المزدوج الأكثر شهرة للوقاية من نزلات البرد وتخفيف أعراض الزكام',
    categoryIcon: '🍊',
    defaultTiming: 'قرص فوار واحد يذاب في كوب ماء يومياً بعد وجبة الإفطار',
    dosageForm: 'أقراص فوارة',
    commonDoses: ['1 قرص فوار يومياً'],
    clinicalNotes: 'يجمع التركيز العالي من فيتامين C مع الزنك لتثبيط تكاثر الفيروسات التنفسية وتقليل مدة الإصابة بالبرد.',
    searchTokens: ['ليمتلس سي زنك', 'limitless c zinc', 'فوار سي زنك', 'فوار ليمتلس برتقال', 'مناعة سي زنك']
  },
  {
    id: 'limitless_osteo',
    tradeName: 'ليميتلس أوستيو فورميولا (Limitless Osteo Formula - Eva)',
    tradeNameEn: 'Limitless Osteo (Calcium Carbonate 600mg + Vit D3 1000IU + Vit K2 MK7 90mcg + Magnesium)',
    scientificName: 'كالسيوم + فيتامين D3 + فيتامين K2 (MK-7) + مغنيسيوم + زنك',
    category: 'joints_bones',
    categoryAr: 'التركيبة الذكية التي ترسب الكالسيوم داخل العظام مباشرة وتمنع ترسبه في الشرايين',
    categoryIcon: '🦴',
    defaultTiming: 'قرص واحد يومياً بعد وجبة الغداء مع كوب ماء',
    dosageForm: 'أقراص مغلفة',
    commonDoses: ['1 قرص يومياً'],
    clinicalNotes: 'ينشط بروتين الأوستيوكالسين عبر فيتامين K2 (MK7)، مما يوجه الكالسيوم للهيكل العظمي ويحمى الشرايين من التكلس.',
    searchTokens: ['ليمتلس اوستيو', 'limitless osteo', 'كالسيوم k2', 'كالسيوم مع فيتامين ك2', 'هشاشة عظام']
  },
  {
    id: 'limitless_coq10',
    tradeName: 'ليميتلس كو إنزيم كيو 10 (Limitless CoQ10 100mg - Eva Pharma)',
    tradeNameEn: 'Limitless CoQ10 100mg Coenzyme Q10 Energy & Fertility Capsules',
    scientificName: 'كوإنزيم كيو 10 (Coenzyme Q10 / Ubiquinone) 100 مجم',
    category: 'supplements',
    categoryAr: 'طاقة الميتوكوندريا، حماية القلب، زيادة جودة البويضات والحيوانات المنوية',
    categoryIcon: '⚡',
    defaultTiming: 'كبسولة واحدة يومياً بعد وجبة الغداء مباشرة',
    dosageForm: 'كبسولات جيلاتينية',
    commonDoses: ['100 مجم يومياً'],
    clinicalNotes: 'محرك طاقة الميتوكوندريا الرئيسي، يرفع الطاقة الخلوية بعضلة القلب ويحسن جودة البويضات عند النساء وحركة الحيوانات المنوية.',
    searchTokens: ['ليمتلس كيو 10', 'limitless coq10', 'كو انزيم كيو 10', 'جودة بويضات', 'خصوبة طاقة']
  },
  {
    id: 'limitless_ashwagandha',
    tradeName: 'ليميتلس أشواجاندا كيه إس إم 66 (Limitless Ashwagandha 600mg KSM-66)',
    tradeNameEn: 'Limitless Ashwagandha KSM-66 Organic Root Extract 600mg',
    scientificName: 'مستخلص جذور الأشواجاندا المعياري المعتمد KSM-66 بتركيز 600 مجم',
    category: 'supplements',
    categoryAr: 'خفض هرمون التوتر الكورتيزول، تحسين النوم العميق، ورفع التستوستيرون والروق العصبية',
    categoryIcon: '🌿',
    defaultTiming: 'كبسولة واحدة مساءً قبل النوم أو بعد العشاء',
    dosageForm: 'كبسولات صلبة',
    commonDoses: ['600 مجم يومياً مساءً'],
    clinicalNotes: 'عشبة الأدابتوجين الأكثر توثيقاً؛ تخفض الكورتيزول بنسبة 30%، تحسن بنية النوم، وترفع القدرة البدنية والذهنية.',
    searchTokens: ['ليمتلس اشواجاندا', 'limitless ashwagandha', 'اشواجاندا ksm66', 'تقليل كورتيزول توتر', 'نوم وعضلات']
  },
  {
    id: 'limitless_probiotics',
    tradeName: 'ليميتلس لاكتو بروبيوتيك (Limitless Lacto Probiotics 10 Billion)',
    tradeNameEn: 'Limitless Lacto Probiotic Digestive Health Capsules (10 Billion CFU + Prebiotics)',
    scientificName: '10 مليارات مستعمرة بكتيريا نافعة (Lactobacillus & Bifidobacterium) + إنولين',
    category: 'gastro',
    categoryAr: 'استعادة توازن ميكروبيوم الأمعاء، علاج انتفاخ القولون العصبي، والحد من الإسهال والغازات',
    categoryIcon: '🫄',
    defaultTiming: 'كبسولة واحدة يومياً قبل الأكل بـ 30 دقيقة أو على معدة فارغة',
    dosageForm: 'كبسولات معوية نباتية',
    commonDoses: ['1 كبسولة 10 مليارات يومياً'],
    clinicalNotes: 'تجديد فلورا الأمعاء بعد تناول المضادات الحيوية، خفض أعراض القولون العصبي، وتعزيز المناعة المعوية.',
    searchTokens: ['ليمتلس بروبيوتيك', 'limitless lacto', 'بكتيريا نافعة ليمتلس', 'قولون عصبي غازات', 'ميكروبيوم']
  },
  {
    id: 'limitless_turmeric',
    tradeName: 'ليميتلس كركمين وكركم (Limitless Turmeric Curcumin - Eva Pharma)',
    tradeNameEn: 'Limitless Turmeric Curcumin (Standardized Curcuminoids 500mg + Piperine Black Pepper)',
    scientificName: 'مستخلص الكركمين المعياري 500 مجم + البيبيرين (الفلفل الأسود لزيادة الامتصاص 2000%)',
    category: 'joints_bones',
    categoryAr: 'مضاد الالتهاب الطبيعي الأقوى لتخفيف التهابات المفاصل والجسد والقولون بدون آثار جانبية',
    categoryIcon: '🌿',
    defaultTiming: 'كبسولة واحدة يومياً بعد وجبة الغداء مع ماء',
    dosageForm: 'كبسولات صلبة',
    commonDoses: ['1 كبسولة يومياً'],
    clinicalNotes: 'يثبط مسارات NF-kB والإنزيمات الالتهابية، مما يمنح تسكيناً طبيعياً لالتهاب المفاصل وتهيج القولون.',
    searchTokens: ['ليمتلس كركمين', 'limitless turmeric', 'كركمين بيبيرين', 'مضاد التهاب طبيعي', 'التهاب مفاصل']
  },
  {
    id: 'perfectil_hair_extra',
    tradeName: 'بيرفيكتيل هير إكسترا سبورت (Perfectil Hair Extra Support - Vitabiotics)',
    tradeNameEn: 'Perfectil Hair Extra Support (Triple Active Micronutrient Formula with Horsetail Extract & Marine Collagen)',
    scientificName: 'مستخلص ذيل الحصان + كولاجين بحري + كيراتين + بيوتين + زنك + 28 المغذيات الدقيقة',
    category: 'supplements',
    categoryAr: 'العلاج الإنجليزي الفاخر لإيقاف تساقط الشعر الشديد وتغذية البصيلات ونمو الشعر بغزارة',
    categoryIcon: '🇬🇧',
    defaultTiming: 'قرصان يومياً مع الوجبة الرئيسية مع كوب ماء بارد',
    dosageForm: 'أقراص مغلفة',
    commonDoses: ['2 قرص يومياً مع الأكل'],
    clinicalNotes: 'يغذي بصيلات الشعر عبر مجرى الدم بـ 28 عنصراً أساسياً، مما يزيد سمك الخصلات ويكثف الشعر خفيف البصيلات.',
    searchTokens: ['بيرفيكتيل', 'perfectil hair', 'بيرفيكتيل اكسترا', 'فيتامين شعر انجليزي', 'تساقط شعر شديد']
  },
  {
    id: 'univita_30_caps',
    tradeName: 'يونيفيتا كبسول (Univita Complete Multivitamin)',
    tradeNameEn: 'Univita Multivitamin & Multimineral Capsules',
    scientificName: 'تركيبة متوازنة من الفيتامينات والمعادن الأساسية والحديد والزنك',
    category: 'supplements',
    categoryAr: 'المكمل الغذائي اليومي الاقتصادي لرفع المناعة والوقاية من نقص المغذيات والإجهاد',
    categoryIcon: '💊',
    defaultTiming: 'كبسولة واحدة يومياً بعد وجبة الإفطار أو الغداء',
    dosageForm: 'كبسولات صلبة',
    commonDoses: ['1 كبسولة يومياً'],
    clinicalNotes: 'يوفر الاحتياج اليومي الأساسي للبالغين للوقاية من سوء التغذية وضعف التركيز.',
    searchTokens: ['يونيفيتا', 'univita', 'كبسول يونيفيتا', 'مالتي فيتامين اقتصادي', 'مقوي عام']
  },
  {
    id: 'biovit_12_depot',
    tradeName: 'بيوفيت 12 أمبول (Biovit 12 Depot Ampoules)',
    tradeNameEn: 'Biovit 12 Depot (Hydroxocobalamin 1000mcg Long Acting Injection)',
    scientificName: 'هيدروكسوكوبالامين فيتامين B12 ممتد المفعول 1000 مكجم',
    category: 'supplements',
    categoryAr: 'حقن ب12 ممتدة المفعول لتقوية الدم والأعصاب وتخفيف الإرهاق المستمر',
    categoryIcon: '💉',
    defaultTiming: 'أمبولة واحدة عضل أسبوعياً أو كل أسبوعين',
    dosageForm: 'أمبولات للحقن العضلي',
    commonDoses: ['1 أمبولة عضل حسَب التعليمات'],
    clinicalNotes: 'توفر خزيناً مستقراً من B12 في الكبد والدم لبناء كيراتين الأعصاب وخلايا الدم الحمراء.',
    searchTokens: ['بيوفيت', 'biovit 12', 'حقن بيوفيت', 'فيتامين ب12 حقن']
  },
  {
    id: 'haemoton_iron_caps',
    tradeName: 'هيموتون كبسول (Haemoton Capsules)',
    tradeNameEn: 'Haemoton Iron & Blood Building Capsules (Ferrous Fumarate + Folic Acid + B12 + Liver Extract)',
    scientificName: 'فيروس فيومارات (حديد) + حمض الفوليك + فيتامين B12 + مستخلص الكبد النقي',
    category: 'supplements',
    categoryAr: 'كبسولات بناء الدم الشاملة لعلاج فقر الدم الشديد وضبط مستويات الهيموجلوبين',
    categoryIcon: '🩸',
    defaultTiming: 'كبسولة واحدة 1-2 مرة يومياً بعد وجبة الغداء مع ماء',
    dosageForm: 'كبسولات صلبة',
    commonDoses: ['1-2 كبسولة يومياً'],
    clinicalNotes: 'تدعم تصنيع خضاب الدم الهيموجلوبين بفضل الجمع بين الحديد وحمض الفوليك ومستخلص الكبد الغني بمساعدات الإنزيمات.',
    searchTokens: ['هيموتون', 'haemoton', 'حديد هيموتون', 'كبسول انيميا', 'رفع هيموجلوبين']
  },
  {
    id: 'madavit_vitastress',
    tradeName: 'مادافيت وفيتاسترس (Madavit / Vitastress B-Complex + Zinc)',
    tradeNameEn: 'Vitastress / Madavit (High Potency B-Complex + Vitamin C 500mg + Zinc)',
    scientificName: 'مجمّع فيتامينات B عالية التركيز + فيتامين ج 500 مجم + زنك عنصري',
    category: 'supplements',
    categoryAr: 'فيتامين الإجهاد والضغوط البدنية والنفسية لرفع الطاقة والمناعة وتنشيط الذهن',
    categoryIcon: '⚡',
    defaultTiming: 'قرص واحد يومياً بعد وجبة الإفطار مع كوب ماء',
    dosageForm: 'أقراص مغلفة',
    commonDoses: ['1 قرص يومياً'],
    clinicalNotes: 'يعوض المستهلك السريع من فيتامينات B والزنك وفيتامين C أثناء التوتر العصبي والإجهاد العضلي والعمل الشاق.',
    searchTokens: ['مادافيت', 'madavit', 'فيتاسترس', 'vitastress', 'فيتامين الضغط والتوتر', 'طاقة ومناعة']
  },
  {
    id: 'araks_peptase_anti',
    tradeName: 'أراكس بيبتيز مضاد التورم (Araks Peptase Tablets)',
    tradeNameEn: 'Araks Peptase Anti-inflammatory Proteolytic Enzyme Tablets',
    scientificName: 'إنزيم السيرا بيبتيز المضاد للتورم والالتهاب (Serratiopeptidase)',
    category: 'supplements',
    categoryAr: 'تفكيك التورمات والتكتلات وتخفيف التهابات المفاصل والجيوب الأنفية والعمليات',
    categoryIcon: '🩹',
    defaultTiming: 'قرص واحد 3 مرات يومياً على معدة فارغة قبل الأكل بساعة',
    dosageForm: 'أقراص مغلفة معوياً',
    commonDoses: ['1 قرص 3 مرات يومياً قبل الأكل'],
    clinicalNotes: 'يهضم البروتينات غير الحية كالتورمات والتكتلات التورمية لتسريع التئام الجروح والجيوب والمفاصل.',
    searchTokens: ['اركس بيبتيز', 'araks peptase', 'مضاد تورم', 'التهاب مفاصل وجيوب']
  },
  {
    id: 'gb_cranberry_144',
    tradeName: 'جي بي كرسي مجرى البول والتوت البري (GB Cranberry 144mg Extract)',
    tradeNameEn: 'GB Cranberry Extract 144mg (Concentrated Proanthocyanidins PACs)',
    scientificName: 'مستخلص ثمار التوت البري الكرانبيري المعياري بمركبات PACs 144 مجم',
    category: 'urology',
    categoryAr: 'منع التصاق بكتيريا E. coli ببطانة مجرى البول وعلاج التهابات المثانة وحرقان البول',
    categoryIcon: '🚻',
    defaultTiming: 'كبسولة واحدة مرتين يومياً بعد الوجبات مع شرب كميات وفيرة من الماء',
    dosageForm: 'كبسولات صلبة',
    commonDoses: ['1 كبسولة مرتين يومياً'],
    clinicalNotes: 'تمنع مركبات البروانثوسيانيدين البكتيريا المسببة لالتهاب المثانة من الالتصاق بجدار مجرى البول، مما يطردها طبيعياً مع البول.',
    searchTokens: ['جي بي توت بري', 'gb cranberry', 'كرانبيري مثانة', 'حرقان بول', 'التهاب مجرى البول']
  },
  {
    id: 'gb_ashwagandha_300',
    tradeName: 'جي بي أشواجاندا 300 مجم (GB Ashwagandha 300mg Extract)',
    tradeNameEn: 'GB Ashwagandha Root Extract 300mg Standardized Withanolides',
    scientificName: 'مستخلص جذور الأشواجاندا المعياري 300 مجم (Withania somnifera)',
    category: 'supplements',
    categoryAr: 'مكافحة التوتر، الاسترخاء، تحسين جودة النوم، ودعم الطاقة والنشاط الهرموني',
    categoryIcon: '🌿',
    defaultTiming: 'كبسولة 1-2 مرة يومياً بعد الأكل مع ماء',
    dosageForm: 'كبسولات صلبة',
    commonDoses: ['300-600 مجم يومياً'],
    clinicalNotes: 'تهدئة الأعصاب وخفض استجابة الجسم للإجهاد اليومي وتحسين التركيز.',
    searchTokens: ['جي بي اشواجاندا', 'gb ashwagandha', 'اشواجاندا جي بي', 'توتر ونوم']
  }
];
