import { EgyptianMedication } from './types';

export const GLOBAL_COMMERCIAL_SUPPLEMENTS: EgyptianMedication[] = [
  // =========================================================================
  // 1. Nootropics, Cognition & Neuro-Protection (منشطات الذهن، التركيز، وتجديد خلايا المخ)
  // =========================================================================
  {
    id: 'lions_mane_mushroom_extract',
    tradeName: 'فطر عرف الأسد المركز (Lion\'s Mane Mushroom 1000mg - Real Mushrooms / NOW Foods)',
    tradeNameEn: 'Organic Lion\'s Mane Mushroom 1000mg 8:1 Dual Extract (Hericium erinaceus)',
    scientificName: 'مستخلص فطر عرف الأسد المعياري العضوي (Hericenones & Erinacines)',
    category: 'supplements',
    categoryAr: 'محفز عامل نمو الأعصاب (NGF)، تجديد خلايا الدماغ، علاج الضباب الذهني، وزيادة التركيز',
    categoryIcon: '🧠',
    defaultTiming: 'كبسولة إلى كبسولتين صباحاً مع وجبة الإفطار أو مع قهوة الصباح',
    dosageForm: 'كبسولات نباتية / مسحوق قابل للخلط',
    commonDoses: ['1000 إلى 2000 مجم يومياً في الصباح'],
    clinicalNotes: 'يعبر الحاجز الدموي الدماغي ويحفز إفراز BDNF و NGF المسؤولين عن اللدونة العصبية (Neuroplasticity) وتكوين مسارات ذاكرة جديدة ومكافحة التدهور الإدراكي والضباب الدماغي.',
    searchTokens: ['عرف الاسد', 'lions mane', 'فطر عرف الاسد', 'ذاكرة', 'تركيز', 'ضباب دماغي', 'ngf', 'اعصاب']
  },
  {
    id: 'alpha_gpc_300_600',
    tradeName: 'ألفا جي بي سي عالي النقاوة (Alpha-GPC 300mg / 600mg - NOW / Thorne)',
    tradeNameEn: 'L-Alpha Glycerylphosphorylcholine (Alpha GPC 300mg/600mg Pharma Grade)',
    scientificName: 'ألفا جليسيريل فوسفوريل كولين النقي المعياري 50% (Alpha GPC)',
    category: 'supplements',
    categoryAr: 'المصدر الأسرع عالمياً لرفع ناقل التعلم والذاكرة الأسيتيل كولين وتحفيز هرمون النمو',
    categoryIcon: '🧠',
    defaultTiming: '300-600 مجم صباحاً قبل العمل المجهد ذهنياً أو قبل التمرين بـ 45 دقيقة',
    dosageForm: 'كبسولات نباتية',
    commonDoses: ['300 إلى 600 مجم يومياً (يفضل الصباح لتجنب النشاط الذهني الزائد ليلاً)'],
    clinicalNotes: 'يوفر الكولين الحيوي المباشر لتصنيع الأسيتيل كولين في المشابك العصبية، مما يرفع سرعة معالجة المعلومات والتركيز اللحظي والاتصال العصبي العضلي (Mind-Muscle Connection).',
    searchTokens: ['الفا جي بي سي', 'alpha gpc', 'كولين مركز', 'اسيتيل كولين', 'سرعة بديهة', 'نوتريبك']
  },
  {
    id: 'bacopa_monnieri_extract',
    tradeName: 'باكوبا مونيري / براهمي (Bacopa Monnieri Synapsa / Bacognize - Doctor\'s Best)',
    tradeNameEn: 'Bacopa Monnieri Extract 300mg Standardized to 50% Bacosides (Synapsa / Bacognize)',
    scientificName: 'مستخلص نبات الباكوبا مونيري القياسي 50% باكوسيدات (Bacosides A & B)',
    category: 'supplements',
    categoryAr: 'عشبة الذاكرة الأيورفيدية العريقة لحفظ المعلومات وسرعة الاسترجاع وتخفيف قلق الاختبارات',
    categoryIcon: '🧠',
    defaultTiming: 'كبسولة واحدة يومياً بعد وجبة غنية بالدهون الصحية (مثل الإفطار أو الغداء)',
    dosageForm: 'كبسولات نباتية',
    commonDoses: ['300 إلى 450 مجم يومياً بصورة مستمرة لمدة 8-12 أسبوعاً'],
    clinicalNotes: 'تدعم ترميم النهايات العصبية التالفة وتوازن النواقل العصبية (الدوبامين والسيروتونين)، وتظهر دراساتها السريرية تحسناً كبيراً في قدرة استرجاع المعلومات وتقليل النسيان العرضي.',
    searchTokens: ['باكوبا', 'bacopa', 'براهمي', 'حفظ وذاكرة', 'مذاكرة', 'استرجاع معلومات']
  },
  {
    id: 'phosphatidylserine_100_300',
    tradeName: 'فوسفاتيديل سيرين (Phosphatidylserine PS 100mg / 300mg - Jarrow / NOW)',
    tradeNameEn: 'Phosphatidylserine Sharp-PS 100mg Non-GMO Soy-Free from Sunflower Lecithin',
    scientificName: 'فوسفاتيديل سيرين نقي مشتق من ليسيثين عباد الشمس (Phosphatidylserine)',
    category: 'supplements',
    categoryAr: 'حماية أغشية خلايا المخ، خفض هرمون التوتر الكورتيزول، وتصفية الذهن',
    categoryIcon: '🧠',
    defaultTiming: '100 مجم مرتين إلى 3 مرات يومياً مع الوجبات، أو 300 مجم بعد التمرين/المساء لخفض الكورتيزول',
    dosageForm: 'كبسولات رخوة / نباتية',
    commonDoses: ['100 إلى 300 مجم يومياً'],
    clinicalNotes: 'المكون الهيكلي الرئيسي لأغشية الخلايا العصبية. يعزز الاتصال بين الخلايا الدماغية، ويتميز بقدرته الإكلينيكية المثبتة على كبح الارتفاع الحاد في هرمون الكورتيزول الناتج عن الإجهاد الذهني والبدني.',
    searchTokens: ['فوسفاتيديل سيرين', 'phosphatidylserine', 'كورتيزول عالي', 'غشاء خلوي', 'ذاكرة كبار السن']
  },
  {
    id: 'l_theanine_suntheanine',
    tradeName: 'إل-ثيانين نقي / صان ثيانين (L-Theanine Suntheanine 200mg - Doctor\'s Best / California Gold)',
    tradeNameEn: 'Suntheanine 100% Pure L-Theanine 200mg (Fermented Green Tea Amino Acid)',
    scientificName: 'إل-ثيانين النقي 200 مجم (Suntheanine L-Theanine)',
    category: 'supplements',
    categoryAr: 'الهدوء المركز وتحفيز موجات ألفا الدماغية والتخلص من رجفة وتوتر الكافيين والقهوة',
    categoryIcon: '🧠',
    defaultTiming: 'كبسولة 200 مجم مع فنجان القهوة الصباحي، أو مساءً قبل النوم للاسترخاء',
    dosageForm: 'كبسولات نباتية',
    commonDoses: ['100 إلى 200 مجم مع الكافيين أو 200-400 مجم للاسترخاء المسائي'],
    clinicalNotes: 'يعبر الحاجز الدموي الدماغي ويزيد موجات ألفا الدماغية (Alpha Brain Waves) المحفزة لحالة الاسترخاء الواعي واليقظة الهادئة (Calm Focus)، ويلغي الأعراض الجانبية للكافيين كالخفقان والقلق.',
    searchTokens: ['ثيانين', 'l theanine', 'suntheanine', 'قهوة بدون توتر', 'موجات الفا', 'تركيز هادئ']
  },
  {
    id: 'l_tyrosine_pure_500',
    tradeName: 'إل-تيروسين 500 مجم (L-Tyrosine - NOW Foods / Thorne)',
    tradeNameEn: 'L-Tyrosine 500mg Free-Form Amino Acid (Dopamine & Adrenaline Precursor)',
    scientificName: 'حمض إل-تيروسين الحر النقي 500 مجم (L-Tyrosine)',
    category: 'supplements',
    categoryAr: 'سلف الدوبامين والنورأدرينالين لرفع الحافز والإنتاجية ومقاومة الضغط النفسي الشديد',
    categoryIcon: '🧠',
    defaultTiming: 'كبسولة إلى كبسولتين صباحاً على معدة فارغة قبل الإفطار بـ 30 دقيقة',
    dosageForm: 'كبسولات نباتية',
    commonDoses: ['500 إلى 1500 مجم صباحاً على الريق'],
    clinicalNotes: 'اللبنة الأساسية لتصنيع هرمونات التحفيز واليقظة (Dopamine & Noradrenaline) وهرمونات الغدة الدرقية (T3 & T4). يمنع استنزاف النواقل العصبية أثناء العمل المكثف وقلة النوم وضغط المواعيد.',
    searchTokens: ['تيروسين', 'l tyrosine', 'دوبامين طبيعي', 'شغف وانتاجية', 'غدة درقية تيروسين']
  },

  // =========================================================================
  // 2. Longevity, Cellular Rejuvenation & Anti-Aging (طول العمر، مكافحة الشيخوخة، وإصلاح الـ DNA)
  // =========================================================================
  {
    id: 'nmn_nicotinamide_mononucleotide',
    tradeName: 'إن إم إن النقي المعتمد (NMN 500mg - ProHealth / Renue / California Gold)',
    tradeNameEn: 'Beta-Nicotinamide Mononucleotide (Uthever Certified Pure NMN 500mg)',
    scientificName: 'بيتا-نيكوتيناميد مونونوكليوتيد فائق النقاوة > 99% (Pure NMN)',
    category: 'supplements',
    categoryAr: 'المحفز المباشر لمستويات NAD+ الخلوية، تنشيط جينات السيرتوين، وتجديد طاقة الميتوكوندريا',
    categoryIcon: '🧬',
    defaultTiming: '500 مجم صباحاً تحت اللسان أو مع ملعقة زيت زيتون / زبادي غني بالدهون',
    dosageForm: 'كبسولات مقاومة للأحماض المعوية / مسحوق يذوب تحت اللسان',
    commonDoses: ['250 إلى 1000 مجم يومياً صباحاً'],
    clinicalNotes: 'يرفع تركيز جزيء الطاقة الخلوية NAD+ الذي يتراجع بنسبة 50% مع التقدم في العمر، مما ينشط إنزيمات السيرتوين (Sirtuins) المسؤولة عن إصلاح التيلوميرات والحمض النووي DNA ومقاومة شيخوخة الخلايا.',
    searchTokens: ['nmn', 'ان ام ان', 'nad', 'تجديد خلايا', 'طول العمر', 'سيرتوين', 'مكافحة الشيخوخة', 'ميتوكوندريا']
  },
  {
    id: 'trans_resveratrol_500',
    tradeName: 'ترانس ريسفيراترول نقي 500 مجم (Trans-Resveratrol 99% - Thorne / ProHealth)',
    tradeNameEn: 'Pure Micronized Trans-Resveratrol 500mg (Polygonum cuspidatum Extract)',
    scientificName: 'ترانس-ريسفيراترول النقي الدقيق الميكروني 500 مجم (Trans-Resveratrol)',
    category: 'supplements',
    categoryAr: 'مضاد الأكسدة البوليفينولي الأقوى لتنشيط جين الشباب SIRT1 وحماية الأوعية الدموية',
    categoryIcon: '🧬',
    defaultTiming: 'كبسولة واحدة صباحاً إلزامياً مع وجبة دهنية أو زيت زيتون (Resveratrol يذوب في الدهون فقط)',
    dosageForm: 'كبسولات نباتية مغلفة لحمايتها من الضوء والأكسدة',
    commonDoses: ['250 إلى 500 مجم يومياً مع الدهون'],
    clinicalNotes: 'يعمل بالتآزر مع NMN؛ حيث يقوم الريسفيراترول بتشغيل جين SIRT1 بينما يوفر NMN الوقود (NAD+) اللازم لعمله. يحمي بطانة الشرايين ويخفض أكسدة الكوليسترول الضار LDL.',
    searchTokens: ['ريسفيراترول', 'resveratrol', 'ترانس ريسفيراترول', 'مضاد اكسدة شرايين', 'جينات الشباب']
  },
  {
    id: 'coq10_ubiquinol_kaneka',
    tradeName: 'يوبيكوينول الصورة النشطة للإنزيم المساعد Q10 (Ubiquinol Kaneka QH 100/200mg - Jarrow / Healthy Origins)',
    tradeNameEn: 'Kaneka Ubiquinol 100mg / 200mg Active Antioxidant Form of CoQ10',
    scientificName: 'يوبيكوينول نقي عالي التوافر الحيوي (Active Reduced Form CoQ10)',
    category: 'supplements',
    categoryAr: 'شاحن طاقة القلب والميتوكوندريا، وعلاج آلام العضلات المصاحبة لأدوية الكوليسترول (الستاتين)',
    categoryIcon: '🧬',
    defaultTiming: 'كبسولة واحدة بعد وجبة الإفطار أو الغداء مع كوب ماء',
    dosageForm: 'كبسولات جيلاتينية رخوة زيتية',
    commonDoses: ['100 إلى 200 مجم يومياً بعد الأكل'],
    clinicalNotes: 'الصورة المختزلة الجاهزة للامتصاص الفوري بنسبة تفوق CoQ10 العادي بـ 8 أضعاف. تعوض استنزاف الإنزيم الناتج عن أدوية الستاتين (أقراص الكوليسترول) وتقوي كفاءة انقباض عضلة القلب.',
    searchTokens: ['يوبيكوينول', 'ubiquinol', 'coq10', 'كانيكا', 'الستاتين والم العضلات', 'طاقة القلب', 'ميتوكوندريا']
  },
  {
    id: 'quercetin_with_bromelain',
    tradeName: 'كيرسيتين مع بروميلين (Quercetin 500mg with Bromelain 200mg - NOW Foods / Thorne)',
    tradeNameEn: 'Quercetin Phytosome / Dihydrate 500mg with Bromelain (Pineapple Enzyme)',
    scientificName: 'فلافونويد الكيرسيتين النقي 500 مجم + إنزيم البروميلين لتسريع الامتصاص',
    category: 'supplements',
    categoryAr: 'حامل الزنك إلى داخل الخلايا (Zinc Ionophore)، مضاد الهيستامين الطبيعي لحساسية الجيوب والصدر',
    categoryIcon: '🧬',
    defaultTiming: 'كبسولة إلى كبسولتين قبل الوجبات بـ 20 دقيقة، أو مع الزنك لتعزيز امتصاصه',
    dosageForm: 'كبسولات نباتية صفراء',
    commonDoses: ['500 مجم مرتين يومياً'],
    clinicalNotes: 'يعمل كأيونوفور طبيعي للزنك يفتح مسام الخلايا لدخول الزنك وإيقاف تكاثر الفيروسات، بالإضافة إلى تثبيط إفراز الهيستامين من الخلايا البدينة (Mast Cells) لعلاج حساسية الصدر والجيوب الأنفية.',
    searchTokens: ['كيرسيتين', 'quercetin', 'بروميلين', 'bromelain', 'حساسية جيوب انفية', 'زنك ايونوفور', 'مناعة فيروسات']
  },
  {
    id: 'fisetin_senolytic_activator',
    tradeName: 'فيسيتين عالي الامتصاص (Fisetin Senolytic Complex 100mg - Life Extension / Doctor\'s Best)',
    tradeNameEn: 'Bio-Fisetin Standardized Extract (Rhus succedanea) with Fenugreek Galactomannans',
    scientificName: 'فيسيتين نباتي نقي معزز بألياف الحلبة لزيادة التوافر الحيوي 25 ضعفاً',
    category: 'supplements',
    categoryAr: 'المنظف الخلوي الأقوى (Senolytic) للتخلص من الخلايا الهرمة وخلايا الزومبي وتجديد الأنسجة',
    categoryIcon: '🧬',
    defaultTiming: 'كبسولة واحدة يومياً مع وجبة دسمة',
    dosageForm: 'كبسولات نباتية مخلبية',
    commonDoses: ['100 مجم يومياً لمدة شهر أو كورس أسبوعي متقطع'],
    clinicalNotes: 'يستهدف الخلايا الشائخة الهرمة غير النشطة (Senescent Zombie Cells) التي تفرز السموم والالتهابات، ويحفز موتها الطبيعي (Apoptosis) ليحل محلها خلايا جذعية فتية ونشطة.',
    searchTokens: ['فيسيتين', 'fisetin', 'تنظيف خلايا', 'سينوليتيك', 'senolytic', 'تجديد شباب الخلايا']
  },

  // =========================================================================
  // 3. Adaptogens, Stress Resilience & Hormonal Vitality (الأدابتوجين، الإجهاد الكظري، والنشاط الهرموني)
  // =========================================================================
  {
    id: 'ashwagandha_ksm66_pure',
    tradeName: 'أشواجاندا كيه إس إم 66 العضوية (Ashwagandha KSM-66 600mg - Jarrow / NOW / Organic India)',
    tradeNameEn: 'KSM-66 Ashwagandha Root Extract 600mg (Standardized 5% Withanolides)',
    scientificName: 'مستخلص جذور العبعب المنوم العضوي الكامل المعياري 5% ويذانوليدات (Withania somnifera)',
    category: 'supplements',
    categoryAr: 'خفض هرمون التوتر الكورتيزول بنسبة 30%، تحسين النوم العميق، ورفع هرمون الذكورة والخصوبة',
    categoryIcon: '🌿',
    defaultTiming: 'كبسولة واحدة مساءً بعد وجبة العشاء أو قبل النوم بساعة مع كوب حليب دافئ أو ماء',
    dosageForm: 'كبسولات نباتية بنية',
    commonDoses: ['300 إلى 600 مجم يومياً في المساء'],
    clinicalNotes: 'المستخلص الأكثر توثيقاً إكلينيكياً في العالم لجذور الأشواجاندا. يثبت نشاط محور الغدة النخامية-الكظرية (HPA Axis)، مما يخفض القلق المزمن ويحسن جودة النوم ويرفع التستوستيرون الطبيعي.',
    searchTokens: ['اشواجاندا', 'أشواجاندا', 'ashwagandha', 'ksm 66', 'كورتيزول عالي', 'توتر وقلق', 'تستوستيرون طبيعي', 'نوم مريح']
  },
  {
    id: 'rhodiola_rosea_3_percent',
    tradeName: 'روديولا روزيا الذهبية (Rhodiola Rosea 500mg - NOW / Thorne)',
    tradeNameEn: 'Rhodiola Rosea Root Extract Standardized 3% Rosavins & 1% Salidroside',
    scientificName: 'مستخلص جذور الروديولا الوردية السيبيرية المعياري (Rosavins & Salidrosides)',
    category: 'supplements',
    categoryAr: 'محاربة الإجهاد المزمن والإرهاق الكظري ورفع الطاقة البدنية دون أي توتر',
    categoryIcon: '🌿',
    defaultTiming: 'كبسولة واحدة صباحاً على معدة فارغة قبل الإفطار بـ 20 دقيقة (تجنب المساء لأنها تمنح طاقة ونشاطاً كبيراً)',
    dosageForm: 'كبسولات نباتية',
    commonDoses: ['250 إلى 500 مجم صباحاً'],
    clinicalNotes: 'عشبة التكيف السيبيرية لحالات الإرهاق والاحتراق النفسي (Burnout). تحمي النواقل العصبية من التكسر وتزيد قدرة تحمل المجهود العضلي والذهني تحت وطأة الضغوط.',
    searchTokens: ['روديولا', 'rhodiola', 'ارهاق مزمن', 'ارهاق كظري', 'burnout', 'طاقة طبيعية']
  },
  {
    id: 'himalayan_shilajit_fulvic',
    tradeName: 'شيلاجيت الهيمالايا النقي عالي الفولفيك (Pure Himalayan Shilajit Resin / 50% Fulvic Acid)',
    tradeNameEn: 'Authentic Wild-Crafted Himalayan Shilajit Resin (Rich in Fulvic Acid & 84+ Trace Minerals)',
    scientificName: 'راتينج الشيلاجيت العضوي النقي المنقى تقليدياً بحمض الفولفيك 50-60%',
    category: 'supplements',
    categoryAr: 'إكسير الطاقة الحيوية، شاحن الميتوكوندريا بـ 84 معدناً نادراً، وتعزيز الخصوبة والتستوستيرون',
    categoryIcon: '🌿',
    defaultTiming: 'حجم حبة البازلاء (300-500 مجم) تذاب في كوب ماء دافئ أو شاي عشبي صباحاً على الريق',
    dosageForm: 'راتينج صمغي أسود نقي / كبسولات جافة معيارية',
    commonDoses: ['250 إلى 500 مجم يومياً صباحاً'],
    clinicalNotes: 'حمض الفولفيك فائق الصغر يعمل كموصل فوري يحمل 84 معدناً أيونياً نادراً مباشرة لداخل الميتوكوندريا، مما يزيد إنتاج ATP الخلوي ويرفع هرمون الذكورة وقوة التحمل البدني.',
    searchTokens: ['شيلاجيت', 'shilajit', 'fulvic acid', 'حمض الفولفيك', 'معادن نادرة', 'طاقة ونشاط رجالي']
  },
  {
    id: 'tongkat_ali_longjack_extract',
    tradeName: 'تونكات علي الأصلي / لونج جاك (Tongkat Ali 200:1 / LJ100 - Double Wood / Solaray)',
    tradeNameEn: 'Tongkat Ali Extract (Eurycoma Longifolia Root Standardized 200:1 / LJ100)',
    scientificName: 'مستخلص جذور تونكات علي المعياري باليوريكوماسين (Eurycomanone 2%)',
    category: 'supplements',
    categoryAr: 'تحرير هرمون التستوستيرون الحر (Free Testosterone) وخفض بروتين SHBG لزيادة القوة والكتلة',
    categoryIcon: '🌿',
    defaultTiming: 'كبسولة 400-500 مجم صباحاً مع الإفطار (يفضل نظام 5 أيام استخدام ويومان راحة)',
    dosageForm: 'كبسولات نباتية',
    commonDoses: ['400 إلى 1000 مجم يومياً بنظام الدورات المتقطعة'],
    clinicalNotes: 'يفك ارتباط هرمون التستوستيرون من بروتين SHBG المقيد، مما يرفع نسبة الهرمون الحر الفعال حيوياً في الدم ويدعم بناء العضلات والدافع الجنسي والأداء الرياضي.',
    searchTokens: ['تونكات علي', 'tongkat ali', 'longjack', 'تستوستيرون حر', 'shbg', 'عضلات وقوة']
  },
  {
    id: 'maca_root_black_yellow',
    tradeName: 'جذور الماكا البيروفية المعالجة بالجيلاتين (Gelatinized Maca Root 1000mg - NOW / California Gold)',
    tradeNameEn: 'Organic Peruvian Maca Root 1000mg (Gelatinized for 99% Digestion & Bioavailability)',
    scientificName: 'مسحوق جذور الماكا العضوية المعالجة جيلاتينياً لنزع النشا المسبب للانتفاخ (Lepidium meyenii)',
    category: 'supplements',
    categoryAr: 'تعزيز الطاقة والتحمل، موازنة الهرمونات الأنثوية والذكورية، وتخفيف هبات الحرارة بعد انقطاع الطمث',
    categoryIcon: '🌿',
    defaultTiming: 'كبسولتان يومياً مع وجبة الإفطار أو الغداء',
    dosageForm: 'كبسولات / مسحوق قابل للإضافة للعصائر',
    commonDoses: ['1000 إلى 3000 مجم يومياً'],
    clinicalNotes: 'الماكا المعالجة بالجيلاتين (Gelatinized) تمت إزالة النشا الخام منها لتكون هينة وسهلة جداً على الجهاز الهضمي. تغذي الغدد الصماء وتزيد الطاقة الجسدية دون رفع ضغط الدم.',
    searchTokens: ['ماكا', 'maca', 'جذور الماكا', 'هرمونات نسائية', 'هبات الحرارة', 'طاقة وتحمل']
  },

  // =========================================================================
  // 4. Advanced Gut, Digestion, Liver & Gallbladder Support (صحة المعدة، الهضم، المرارة، والديتوكس)
  // =========================================================================
  {
    id: 'nac_n_acetyl_cysteine_600_1000',
    tradeName: 'إن-أسيتيل سيستين / أستيل سيستايين (NAC 600mg / 1000mg - NOW / Thorne / فوار مصر)',
    tradeNameEn: 'N-Acetyl L-Cysteine (NAC) 600mg / 1000mg Free-Radical Protection',
    scientificName: 'إن-أسيتيل إل-سيستين النقي (N-Acetyl Cysteine)',
    category: 'supplements',
    categoryAr: 'السلف المباشر لأقوى مضاد أكسدة في الجسم (الجلوتاثيون)، مذيب للبلغم، وحامي خلايا الكبد والرئة',
    categoryIcon: '🫁',
    defaultTiming: 'كبسولة أو كيس فوار على معدة فارغة مع كوب ماء كبير صباحاً ومساءً',
    dosageForm: 'كبسولات / أكياس فوارة سريعة الذوبان',
    commonDoses: ['600 إلى 1200 مجم يومياً'],
    clinicalNotes: 'يوفر الحمض الأميني السيستين الحرج لتصنيع الجلوتاثيون الكبدي والرئوي. يفكك الروابط الكبريتية في المخاط الكثيف بالجهاز التنفسي ويحمي الكبد من السموم والشوارد الحرة.',
    searchTokens: ['nac', 'ناك', 'اسيتيل سيستايين', 'acetylcysteine', 'جلوتاثيون', 'تنظيف كبد ورئة', 'مذيب بلغم']
  },
  {
    id: 'tudca_liver_bile_acid',
    tradeName: 'تودكا حمض الصفراء المتقلب (TUDCA 250mg / 500mg - Double Wood / Nutricost)',
    tradeNameEn: 'Tauroursodeoxycholic Acid (TUDCA 250mg/500mg Water-Soluble Bile Acid)',
    scientificName: 'حمض التورورسوديوكسيكوليك الذائب في الماء النقي (TUDCA)',
    category: 'supplements',
    categoryAr: 'منظف القنوات الصفراوية، إذابة ركود المرارة، وحماية خلايا الكبد من الإجهاد التأكسدي والتليف',
    categoryIcon: '🫄',
    defaultTiming: 'كبسولة واحدة (250-500 مجم) مع وجبة الغداء الدسمة',
    dosageForm: 'كبسولات صلبة نقية',
    commonDoses: ['250 إلى 500 مجم يومياً مع الوجبات المحتوية على دهون'],
    clinicalNotes: 'حمض صفراوي داخلي ذائب في الماء يحمي شبكة الإندوبلازميك ريتيكيولم داخل خلايا الكبد، ويسيل العصارة الصفراوية اللزجة ويمنع انسداد القنوات المرارية وحصوات الكوليسترول.',
    searchTokens: ['تودكا', 'tudca', 'مرارة', 'قنوات صفراوية', 'دهون كبد متقدمة', 'انزيمات كبد']
  },
  {
    id: 'betaine_hcl_pepsin',
    tradeName: 'بيتايين هيدروكلوريد مع بيبسين (Betaine HCl 650mg + Pepsin - Doctor\'s Best / NOW Foods)',
    tradeNameEn: 'Betaine Hydrochloride 650mg with Pepsin Acid-Stable Protease Enzyme',
    scientificName: 'بيتايين حمضي هيدروكلوريد + إنزيم هضم البروتين بيبسين الفعال',
    category: 'supplements',
    categoryAr: 'علاج نقص حموضة المعدة، عسر هضم اللحوم والبروتينات، والتجشؤ والانتفاخ بعد الطعام',
    categoryIcon: '🫄',
    defaultTiming: 'كبسولة إلى كبسولتين وسط الوجبة الرئيسية الغنية بالبروتين (اللحوم والدواجن والأسماك). تنبيه: لا تتناولها مع وجبات خالية من البروتين!',
    dosageForm: 'كبسولات معوية حامضية',
    commonDoses: ['650 مجم وسط وجبة البروتين'],
    clinicalNotes: 'يعيد درجة حموضة المعدة لمستواها المثالي الفسيولوجي (pH 1.5-2.0) الضروري لتنشيط إنزيم البيبسين لهضم البروتين وامتصاص فيتامين B12 والحديد والكالسيوم وإغلاق صمام الفؤاد لمنع الارتجاع.',
    searchTokens: ['بيتايين', 'betaine hcl', 'بيبسين', 'حمض المعدة', 'عسر هضم لحوم', 'ارتجاع المريء']
  },
  {
    id: 'zinc_l_carnosine_pepzin_gi',
    tradeName: 'زنك إل-كارنوزين المرمم للمعدة (Zinc L-Carnosine / PepZin GI - Doctor\'s Best / NOW)',
    tradeNameEn: 'PepZin GI Patented Zinc-Carnosine Chelate 75mg (Zinc 16mg + L-Carnosine 59mg)',
    scientificName: 'مركب مخلبي متكامل يجمع بين معدن الزنك وحمض الكارنوزين (Zinc-Carnosine Complex)',
    category: 'supplements',
    categoryAr: 'ترميم بطانة المعدة المتآكلة، علاج التهاب وقرحة المعدة وجرثومة المعدة H. Pylori',
    categoryIcon: '🫄',
    defaultTiming: 'كبسولة واحدة صباحاً على معدة فارغة وكبسولة قبل النوم',
    dosageForm: 'كبسولات نباتية لطيفة',
    commonDoses: ['75 مجم مرتين يومياً لمدة 8 أسابيع'],
    clinicalNotes: 'يلتصق نوعياً بالمناطق المتقرحة والملتهبة في جدار المعدة والمريء، ويبقى ملتصقاً لفترة طويلة ليفرز الزنك المساعد على التئام الأنسجة المخاطية وإفراز طبقة الميوسين الواقية.',
    searchTokens: ['زنك كارنوزين', 'pepzin gi', 'zinc carnosine', 'قرحة معدة', 'جرثومة المعدة', 'ترميم جدار المعدة']
  },
  {
    id: 'digestive_enzymes_complex',
    tradeName: 'إنزيمات الهضم الشاملة واسعة النطاق (Super Enzymes - NOW Foods / Doctor\'s Best)',
    tradeNameEn: 'Comprehensive Full-Spectrum Digestive Enzymes (Pancreatin, Ox Bile, Bromelain, Papain, Lipase, Lactase)',
    scientificName: 'مزيج إنزيمات هاضمة: أميليز، بروتياز، ليبيز، لاكتيز، بابين، بروميلين، وعصارة المرارة (Ox Bile)',
    category: 'supplements',
    categoryAr: 'الهضم الفوري للدهون الدسمة، اللاكتوز، والنشويات لمنع التخمر والغازات وثقل البطن',
    categoryIcon: '🫄',
    defaultTiming: 'قرص واحد أو كبسولة مع أول لقمة من الوجبة الدسمة مباشرة',
    dosageForm: 'أقراص أو كبسولات معوية',
    commonDoses: ['1 كبسولة مع كل وجبة دسمة أو محتوية على ألبان'],
    clinicalNotes: 'يغطي كافة مسارات تفكيك الطعام الثلاثية (الدهون، الكربوهيدرات، والبروتينات) بالإضافة لإنزيم اللاكتيز لهضم سكر الحليب لمرضى عدم تحمل اللاكتوز (Lactose Intolerance).',
    searchTokens: ['انزيمات هضم', 'digestive enzymes', 'super enzymes', 'غازات بعد الاكل', 'لاكتيز', 'عصارة مرارة']
  },
  {
    id: 'dgl_deglycyrrhizinated_licorice',
    tradeName: 'عرق سوس منزوع الجلسريزين دي جي إل (DGL Licorice Chewable - Nature\'s Way / NOW)',
    tradeNameEn: 'DGL (Deglycyrrhizinated Licorice Extract) 400mg-760mg Chewable Tablets',
    scientificName: 'مستخلص جذور العرق سوس منزوع حمض الجلسريزين بنسبة > 98% (DGL)',
    category: 'supplements',
    categoryAr: 'تهدئة حموضة وحرقة المريء والمعدة الفورية دون التسبب في أي رفع لضغط الدم',
    categoryIcon: '🫄',
    defaultTiming: 'قرص إلى قرصين للمضغ قبل الوجبات بـ 20 دقيقة أو عند الشعور بالحموضة',
    dosageForm: 'أقراص مضغ بنكهة طبيعية لذيذة',
    commonDoses: ['1-2 قرص للمضغ قبل الأكل وعند اللزوم'],
    clinicalNotes: 'نزع مادة الجلسريزين (Glycyrrhizin) يجعل العشبة آمنة تماماً لمرضى الضغط المرتفع والقلب، حيث تزيد إفراز المخاط الواقي للمعدة والمريء فور مضغها وتلامسها مع اللعاب.',
    searchTokens: ['dgl', 'عرق سوس منزوع الجلسريزين', 'حموضة مريء', 'حرقان معدة', 'عرق سوس امن للضغط']
  },

  // =========================================================================
  // 5. Advanced Minerals & High Bioavailability Chelates (المعادن المخلبية فائقة النقاء والامتصاص)
  // =========================================================================
  {
    id: 'magnesium_l_threonate_magtein',
    tradeName: 'مغنيسيوم إل-ثريونات ماجتين المخصص للدماغ (Magnesium L-Threonate / Magtein - NOW / Life Extension)',
    tradeNameEn: 'Magtein Magnesium L-Threonate (The Only Form Proven to Cross Blood-Brain Barrier)',
    scientificName: 'ماجتين: مغنيسيوم مخلبي مع حمض الثريونيك (Magnesium L-Threonate 2000mg yielding 144mg Elemental Mg)',
    category: 'supplements',
    categoryAr: 'الصورة الوحيدة للمغنيسيوم التي تخترق الحاجز الدموي الدماغي لتكثيف الوصلات العصبية والنوم العميق',
    categoryIcon: '💊',
    defaultTiming: 'كبسولة صباحاً وكبسولتان قبل النوم بساعة',
    dosageForm: 'كبسولات نباتية نقية',
    commonDoses: ['1500 إلى 2000 مجم يومياً (توفر 144 مجم مغنيسيوم عنصري نقي للدماغ)'],
    clinicalNotes: 'تم تطويره في معهد ماساتشوستس للتكنولوجيا (MIT)؛ حيث يرفع كثافة المشابك العصبية في منطقة الحصين (Hippocampus) بالدماغ، ويحسن الذاكرة قصيرة وطويلة المدى وجودة مراحل النوم العميق.',
    searchTokens: ['مغنيسيوم ثريونات', 'magtein', 'magnesium l threonate', 'مغنيسيوم للدماغ', 'نوم وذاكرة', 'مغنيسيوم اعصاب']
  },
  {
    id: 'magnesium_bisglycinate_traacs',
    tradeName: 'مغنيسيوم بيسجلايسينات المخلبي تراككس (Magnesium Bisglycinate Chelate TRAACS - Thorne / Doctor\'s Best)',
    tradeNameEn: '100% Chelated Magnesium Bisglycinate (Albion Minerals TRAACS) 200mg Elemental',
    scientificName: 'مغنيسيوم مرتبط بحمضين جلايسين مخلبياً فائق الامتصاص واللطافة على المعدة',
    category: 'supplements',
    categoryAr: 'إرخاء العضلات، منع الشد العضلي الليلي، تهدئة الجهاز العصبي، وبدون أي أثر ملين للمعدة',
    categoryIcon: '💊',
    defaultTiming: 'قرص أو كبسولتان مساءً بعد العشاء أو قبل النوم بساعة مع ماء',
    dosageForm: 'أقراص / كبسولات مخلبية',
    commonDoses: ['200 إلى 400 مجم مغنيسيوم عنصري مخلبي يومياً'],
    clinicalNotes: 'محمي بروابط الجلايسين الثنائية التي تمنع تفككه المبكر في المعدة، فيمتص عبر قنوات الببتيد في الأمعاء بنسبة 90% دون سحب الماء أو التسبب في إسهال كالمغنيسيوم أوكسيد.',
    searchTokens: ['مغنيسيوم بيسجلايسينات', 'magnesium glycinate', 'traacs', 'شد عضلي', 'ارق وتوتر', 'مغنيسيوم مخلبي']
  },
  {
    id: 'iron_bisglycinate_gentle_ferrochel',
    tradeName: 'حديد مخلبي لطيف على المعدة (Gentle Iron Ferrochel 25mg / 36mg - Solgar / NOW)',
    tradeNameEn: 'Ferrochel Iron Bisglycinate Chelate 25mg-36mg Non-Constipating Formula',
    scientificName: 'حديد ثنائي الجلايسين المخلبي النقي (Ferrous Bisglycinate Chelate - Albion)',
    category: 'supplements',
    categoryAr: 'رفع مخزون الحديد (الفيريتين) والهيموجلوبين سريعاً بدون إمساك أو آلام معدة أو طعم معدني',
    categoryIcon: '💊',
    defaultTiming: 'كبسولة واحدة يومياً بعد وجبة الإفطار أو الغداء بساعتين مع كوب عصير برتقال (فيتامين C يزيد الامتصاص)',
    dosageForm: 'كبسولات نباتية لطيفة',
    commonDoses: ['25 إلى 50 مجم حديد مخلبي عنصري يومياً'],
    clinicalNotes: 'لا يتأثر بمثبطات الامتصاص كالفيتات وحمض التانيك في الشاي والقهوة بنفس درجة أملاح الحديد العادية، ولا يسبب أكسدة أو تهيجاً لبطانة الأمعاء، مما يقضي على الإمساك والغثيان المعتاد.',
    searchTokens: ['حديد مخلبي', 'gentle iron', 'ferrochel', 'انيميا بدون امساك', 'مخزون حديد', 'فيريتين']
  },
  {
    id: 'l_selenomethionine_200mcg',
    tradeName: 'سيلينيوم عضوي نقي (Selenium L-Selenomethionine 200mcg - NOW / Thorne)',
    tradeNameEn: 'Yeast-Free High-Potency L-Selenomethionine 200mcg Antioxidant',
    scientificName: 'سيلينوميثيونين نقي عضوي خالي من الخميرة 200 ميكروجرام (L-Selenomethionine)',
    category: 'supplements',
    categoryAr: 'خفض الأجسام المضادة للغدة الدرقية (Anti-TPO لمرضى هاشيموتو) وحماية البروستاتا والمناعة',
    categoryIcon: '💊',
    defaultTiming: 'كبسولة واحدة يومياً بعد وجبة الإفطار أو الغداء مع كوب ماء',
    dosageForm: 'كبسولات نباتية صغيرة',
    commonDoses: ['100 إلى 200 ميكروجرام يومياً (تجنب تجاوز 400 مكجم)'],
    clinicalNotes: 'عنصر لا غنى عنه لتشغيل إنزيمات Deiodinase المسؤولة عن تحويل هرمون الغدة الدرقية الخامل T4 إلى T3 الفعال، كما ينشط إنزيم الجلوتاثيون بيروكسيداز لحماية أنسجة الغدة من التلف المناعي.',
    searchTokens: ['سيلينيوم', 'selenium', 'سيلينوميثيونين', 'هاشيموتو', 'خمول الغدة الدرقية', 'anti tpo']
  },
  {
    id: 'boron_glycinate_chelated',
    tradeName: 'بورون مخلبي عالي الفعالية (Triple Boron Complex 3mg-6mg - Swanson / NOW Foods)',
    tradeNameEn: 'Triple Boron Complex (Citrate, Aspartate, Glycinate) 3mg-6mg',
    scientificName: 'مركب البورون الثلاثي المخلبي (Boron Glycinate Complex)',
    category: 'supplements',
    categoryAr: 'تثبيت الكالسيوم والمغنيسيوم في العظام، خفض هرمون الإستروجين الضار، ورفع التستوستيرون الحر',
    categoryIcon: '💊',
    defaultTiming: 'كبسولة واحدة (3-6 مجم) صباحاً بعد وجبة الإفطار',
    dosageForm: 'كبسولات صلبة',
    commonDoses: ['3 إلى 6 مجم يومياً كورس لمدة شهرين'],
    clinicalNotes: 'يقلل إفراز الكالسيوم والمغنيسيوم والفسفور في البول، ويخفض بروتين SHBG المقيد لهرمونات الذكورة بنسبة 28% في الدراسات السريرية، مما يرفع كفاءة البناء العضلي وكثافة العظام.',
    searchTokens: ['بورون', 'boron', 'تثبيت الكالسيوم', 'تستوستيرون بورون', 'shbg']
  },
  {
    id: 'kelp_iodine_seaweed',
    tradeName: 'يود طبيعي من عشب البحر كيلب (Sea Kelp Natural Iodine 150-325mcg - Nature\'s Way / NOW)',
    tradeNameEn: 'Organic Icelandic Sea Kelp Standardized to 225mcg-325mcg Pure Iodine',
    scientificName: 'مستخلص عشب البحر البني الآيسلندي العضوي النقي (Laminaria Digitata)',
    category: 'supplements',
    categoryAr: 'الوقود الطبيعي لتصنيع هرمونات الغدة الدرقية وتنشيط الأيض ومكافحة برودة الأطراف',
    categoryIcon: '🦋',
    defaultTiming: 'قرص واحد يومياً صباحاً مع وجبة الإفطار',
    dosageForm: 'أقراص عشبية مضغوطة',
    commonDoses: ['150 إلى 225 ميكروجرام يومياً'],
    clinicalNotes: 'المصدر العضوي الأفضل لليود الأيوني الطبيعي المحاط بالمعادن البحرية، ضروري لتخليق جزيئات هرمون الثيروكسين (T4) لمن لا يتناولون الملح المعالج باليود أو المأكولات البحرية بانتظام.',
    searchTokens: ['يود', 'iodine', 'كيلب', 'kelp', 'عشب البحر', 'يود الغدة الدرقية', 'نشاط الايض']
  },

  // =========================================================================
  // 6. Sports Performance, Muscle Mass & Recovery (الأداء الرياضي، الكتلة العضلية، والتحمل)
  // =========================================================================
  {
    id: 'creatine_monohydrate_creapure',
    tradeName: 'كرياتين مونوهيدرات نقي كريابيور (Creapure Creatine Monohydrate 5g - Optimum Nutrition / Thorne)',
    tradeNameEn: '100% Pure Micronized Creapure Creatine Monohydrate (Made in Germany 99.99%)',
    scientificName: 'كرياتين مونوهيدرات ميكروني ألماني فائق النقاوة (Creapure)',
    category: 'supplements',
    categoryAr: 'المكمل الرياضي رقم 1 عالمياً لزيادة القوة الانفجارية، حجم الألياف العضلية، والوظائف الإدراكية للدماغ',
    categoryIcon: '🏋️',
    defaultTiming: '5 جرام (مكيال) يومياً يذاب في ماء أو عصير بعد التمرين أو في أي وقت ثابت مع شرب 3-4 لتر ماء يومياً',
    dosageForm: 'بودرة بيضاء نقية سريعة الذوبان عديمة النكهة',
    commonDoses: ['5 جرامات يومياً بصفة مستمرة (لا يشترط فترة تحميل)'],
    clinicalNotes: 'يشحن مخازن الفوسفوكرياتين (Phosphocreatine) في العضلات والمخ لإعادة تدوير ATP الفوري أثناء الانقباضات الشديدة، ويسحب الماء لداخل الخلايا العضلية (Intracellular Hydration) لتحفيز التخليق البروتيني.',
    searchTokens: ['كرياتين', 'creatine', 'كريابيور', 'creapure', 'قوة عضلية', 'بناء عضلات', 'كرياتين صافي']
  },
  {
    id: 'l_citrulline_malate_2_1',
    tradeName: 'إل-سيترولين مالات 2:1 لضخ الدم (L-Citrulline Malate 2:1 - Nutricost / AllMax / Kaged)',
    tradeNameEn: 'Pure Fermented L-Citrulline Malate 2:1 Ratio (6000mg-8000mg Pump & Endurance)',
    scientificName: 'حمض إل-سيترولين النقي مرتبط بحمض الماليك بنسبة 2:1 (Citrulline Malate)',
    category: 'supplements',
    categoryAr: 'توسيع الشرايين، مضخة الدم العضلية (Muscle Pump)، خفض ضغط الدم، ومكافحة إجهاد التمرين',
    categoryIcon: '🏋️',
    defaultTiming: '6 إلى 8 جرامات تذاب في ماء وتشرب قبل التمرين بـ 30-45 دقيقة (Pre-Workout)',
    dosageForm: 'بودرة نقية ذات مذاق حامضي منعش',
    commonDoses: ['6 إلى 8 جرامات قبل التمرين'],
    clinicalNotes: 'يتفوق على الأرجينين في رفع مستويات أكسيد النيتريك (Nitric Oxide) في الدم بنسبة مضاعفة لأنه يتجاوز استقلاب الكبد، مما يوسع الأوعية الدموية ويزيد تدفق الأكسجين والمغذيات للعضلات العاملة.',
    searchTokens: ['سيترولين', 'citrulline', 'سيترولين مالات', 'ضخ دم', 'مكمل قبل التمرين', 'اكسيد النيتريك', 'نيتريك اوكسايد']
  },
  {
    id: 'beta_alanine_carnosyn',
    tradeName: 'بيتا-ألانين كارنوسين لتحمل الجهد (Beta-Alanine CarnoSyn 3.2g - NOW / PrimaForce)',
    tradeNameEn: 'CarnoSyn Beta-Alanine 3200mg (Muscle Carnosine Booster & Lactic Acid Buffer)',
    scientificName: 'حمض بيتا-ألانين النقي المعياري المعتمد (CarnoSyn Pure Beta-Alanine)',
    category: 'supplements',
    categoryAr: 'تأخير حمض اللاكتيك وإجهاد العضلات، زيادة عدد التكرارات، وزيادة كفاءة العدو والمجهود العالي',
    categoryIcon: '🏋️',
    defaultTiming: '3.2 إلى 5 جرامات مقسمة على جرعتين (مثلاً 2 جرام قبل التمرين و 2 جرام بعده) لتقليل الشعور بالتنميل الجلدي المؤقت (Paresthesia)',
    dosageForm: 'بودرة / كبسولات',
    commonDoses: ['3.2 إلى 6.4 جرام يومياً'],
    clinicalNotes: 'يتحد مع الهيستيدين لتكوين مركب الكارنوزين (Carnosine) داخل ألياف العضلات، والذي يعمل كدارئ حامضي (Acid Buffer) يمتص أيونات الهيدروجين ويمنع هبوط الـ pH المسبب للحرقة والإجهاد العضلي.',
    searchTokens: ['بيتا الانين', 'beta alanine', 'كارنوسين', 'تنميل العضلات', 'تحمل تمرين', 'حمض اللاكتيك']
  },
  {
    id: 'hmb_calcium_myoleptin',
    tradeName: 'إتش إم بي النقي لمنع الهدم العضلي (HMB 1000mg-3000mg - MuscleTech / Nutricost)',
    tradeNameEn: 'Calcium HMB (Beta-Hydroxy Beta-Methylbutyrate 1000mg) Anti-Catabolic',
    scientificName: 'هيدروكسي بيتا ميثيل بيوتيرات الكالسيوم (Calcium Beta-Hydroxy Beta-Methylbutyrate)',
    category: 'supplements',
    categoryAr: 'الحارس الأقوى ضد هدم الألياف العضلية أثناء الدايت القاسي، الصيام المتقطع، وكبار السن',
    categoryIcon: '🏋️',
    defaultTiming: 'كبسولة 1000 مجم 3 مرات يومياً مع الوجبات، أو 3000 مجم قبل تمرين الصيام',
    dosageForm: 'كبسولات / مسحوق',
    commonDoses: ['3000 مجم (3 جم) يومياً مقسمة على جرعات'],
    clinicalNotes: 'المستقلب النشط لحمض الليوسين؛ يثبط مسار التكسير البروتيني (Ubiquitin-Proteasome System) ويحمي العضلات من الضمور أثناء عجز السعرات الشديد وفترات النقاهة بعد الإصابات.',
    searchTokens: ['hmb', 'اتش ام بي', 'منع هدم العضلات', 'تنشيف عضلات', 'صيام متقطع هدم']
  },
  {
    id: 'tart_cherry_extract_recovery',
    tradeName: 'مستخلص الكرز الحامض تارت شيري (Tart Cherry Extract 1000mg - Solaray / NOW Foods)',
    tradeNameEn: 'Montmorency Tart Cherry Fruit Extract Standardized Anthocyanins (Uric Acid & Muscle Recovery)',
    scientificName: 'مستخلص ثمار الكرز الحامض مونتمورنسي الغني بالأنثوسيانين والميلاتونين الطبيعي',
    category: 'supplements',
    categoryAr: 'سرعة الاستشفاء العضلي بعد التمارين الشاقة، خفض حمض اليوريك أسيد، وتحسين جودة النوم',
    categoryIcon: '🍒',
    defaultTiming: 'كبسولة إلى كبسولتين مساءً بعد وجبة العشاء مع كوب ماء',
    dosageForm: 'كبسولات نباتية / عصير مركز',
    commonDoses: ['1000 إلى 2500 مجم يومياً في المساء'],
    clinicalNotes: 'تخفض البوليفينولات والأنثوسيانين في الكرز الحامض علامات الالتهاب والتلف العضلي (CK & CRP) بشكل ملحوظ، وتساعد الكلى على تصريف بلورات اليوريك أسيد ومكافحة نوبات النقرس والوجع العضلي المتأخر (DOMS).',
    searchTokens: ['تارت شيري', 'tart cherry', 'كرز حامض', 'يوريك اسيد', 'استشفاء عضلي', 'doms']
  },

  // =========================================================================
  // 7. Hair Density, Skin Radiance & Nails (كثافة الشعر، نضارة البشرة، وصحة الأظافر)
  // =========================================================================
  {
    id: 'saw_palmetto_hair_dht',
    tradeName: 'بلميط منشاري معياري لتساقط الشعر والبروستاتا (Saw Palmetto 320mg 85-95% Fatty Acids - NOW / Havasu)',
    tradeNameEn: 'Saw Palmetto Berry Extract Standardized to 85%-95% Fatty Acids & Sterols',
    scientificName: 'مستخلص ثمار البلميط المنشاري المعياري (Serenoa repens 320mg)',
    category: 'supplements',
    categoryAr: 'المثبط النباتي الطبيعي لإنزيم 5-Alpha Reductase لوقف تساقط الشعر الهرموني والصلع الوراثي',
    categoryIcon: '💇',
    defaultTiming: 'كبسولة جيلاتينية واحدة (320 مجم) أو كبسولتان (160 مجم) يومياً مع وجبة دسمة',
    dosageForm: 'كبسولات جيلاتينية رخوة زيتية داكنة',
    commonDoses: ['320 مجم يومياً بعد الأكل'],
    clinicalNotes: 'يمنع تحول هرمون التستوستيرون إلى ثنائي هيدروتستوستيرون (DHT) المسؤول عن ضمور بصيلات الشعر التاجية في الرجال والنساء وتضخم البروستاتا، دون إحداث آثار جانبية جنسية مزعجة.',
    searchTokens: ['بلميط منشاري', 'saw palmetto', 'تساقط شعر وراثي', 'dht blocker', 'صلع هرموني']
  },
  {
    id: 'biotin_10000_coconut',
    tradeName: 'بيوتين عالي التركيز مع زيت جوز الهند (Biotin 10,000mcg - Sports Research / NOW Foods)',
    tradeNameEn: 'High Potency Biotin (Vitamin B7) 10,000mcg in Organic Virgin Cold-Pressed Coconut Oil',
    scientificName: 'د-بيوتين النقي 10,000 ميكروجرام (Pure D-Biotin / Vitamin B7)',
    category: 'supplements',
    categoryAr: 'تقوية روابط الكيراتين في الشعر، علاج تقصف وتكسر الأظافر، وتحسين نضارة البشرة',
    categoryIcon: '💇',
    defaultTiming: 'كبسولة واحدة يومياً بعد وجبة الإفطار أو الغداء مباشرة مع كوب ماء كامل',
    dosageForm: 'كبسولات جيلاتينية رخوة في زيت جوز الهند',
    commonDoses: ['5,000 إلى 10,000 ميكروجرام يومياً'],
    clinicalNotes: 'يعمل كإنزيم مساعد في أيض الأحماض الدهنية والأمينية الضرورية لتخليق ألياف الكيراتين الصلبة في بصيلات الشعر وصفائح الأظافر. تنبيه سريري: يجب إيقافه قبل تحاليل الغدة الدرقية بـ 48 ساعة لتجنب القراءات الخاطئة.',
    searchTokens: ['بيوتين', 'biotin', 'بيوتين 10000', 'كيراتين شعر', 'تقصف اظافر', 'فيتامين ب7']
  },
  {
    id: 'marine_collagen_hyaluronic_vitc',
    tradeName: 'كولاجين بحري متحلل مع حمض الهيالورونيك وفيتامين C (California Gold Nutrition CollagenUp 5000mg)',
    tradeNameEn: 'CollagenUp Hydrolyzed Marine Collagen Peptides + Hyaluronic Acid + Vitamin C (CGN)',
    scientificName: 'ببتيدات كولاجين السمك المتحللة مائياً منخفضة الوزن الجزيئي + هيالورونات الصوديوم',
    category: 'supplements',
    categoryAr: 'النضارة والترطيب العميق للبشرة، مكافحة التجاعيد والخطوط الدقيقة، وترميم الغضاريف',
    categoryIcon: '✨',
    defaultTiming: 'مكيال واحد يذاب في كوب ماء أو عصير حمضي صباحاً على الريق قبل الإفطار بـ 30 دقيقة',
    dosageForm: 'بودرة فورية نقية عديمة الرائحة',
    commonDoses: ['5 إلى 10 جرامات يومياً على معدة فارغة'],
    clinicalNotes: 'الكولاجين البحري يتميز بحجم جزيئي أصغر بمقدار 1.5 مرة من الكولاجين البقري، مما يعطيه سرعة امتصاص ونفاذية فائقة لأنسجة الأدمة والمفاصل، بينما يحافظ الهيالورونيك على احتباس الرطوبة في الجلد.',
    searchTokens: ['كولاجين اب', 'collagenup', 'كولاجين بحري', 'هيالورونيك اسيد', 'نضارة بشرة', 'تجاعيد']
  },
  {
    id: 'astaxanthin_12mg_pure',
    tradeName: 'أستازانثين الملك الأقوى لمضادات الأكسدة (Astaxanthin 12mg - Sports Research / BioAstin)',
    tradeNameEn: 'Natural Astaxanthin 12mg from Hawaiian Microalgae (Haematococcus pluvialis) in Coconut MCT',
    scientificName: 'أستازانثين نقي مشتق من طحالب الهيماتوكوكس الطبيعية (Astaxanthin 12mg)',
    category: 'supplements',
    categoryAr: 'مضاد أكسدة أقوى بـ 6000 مرة من فيتامين C، حماية خلايا الجلد وشبكية العين من الأشعة فوق البنفسجية',
    categoryIcon: '✨',
    defaultTiming: 'كبسولة جيلاتينية حمراء واحدة يومياً بعد وجبة غنية بالدهون الصحية',
    dosageForm: 'كبسولات رخوة حمراء داكنة',
    commonDoses: ['4 إلى 12 مجم يومياً مع الوجبات الدهنية'],
    clinicalNotes: 'الوحيد القادر على اختراق الطبقتين المزدوجتين للغشاء الخلوي لحماية الخلية من الداخل والخارج معاً. يحمي شبكية العين من إجهاد الشاشات والضوء الأزرق ويمنع التصبغات وشيخوخة الجلد الناتجة عن الشمس.',
    searchTokens: ['استازانثين', 'astaxanthin', 'اقوى مضاد اكسدة', 'حماية العين', 'نضارة وتجاعيد', 'شاشات وضوء ازرق']
  },
  {
    id: 'msm_methylsulfonylmethane_1000',
    tradeName: 'إم إس إم الكبريت العضوي النقي (OptiMSM 1000mg - Doctor\'s Best / NOW Foods)',
    tradeNameEn: 'Pure OptiMSM (Methylsulfonylmethane) 1000mg Organic Bioavailable Sulfur',
    scientificName: 'ميثيل سلفونيل ميثان النقي المقطر ربعياً (OptiMSM Pure Flakes)',
    category: 'supplements',
    categoryAr: 'تكوين الروابط الكبريتية للكيراتين والكولاجين، إيقاف تساقط الشعر، وتسكين التهابات المفاصل',
    categoryIcon: '🦴',
    defaultTiming: 'كبسولة إلى كبسولتين صباحاً ومساءً مع الوجبات وفيتامين C لتعظيم الفاعلية',
    dosageForm: 'كبسولات نباتية / بلورات مسحوق',
    commonDoses: ['1000 إلى 3000 مجم يومياً'],
    clinicalNotes: 'الكبريت العضوي هو المعدن الرابع الأكثر وفرة في الجسم، يشكل الجسور الكبريتية (Disulfide Bonds) التي تعطي خصلة الشعر قوتها ومتانتها وتمنع تكسر الأظافر وتخفف التصلب الصباحي للمفاصل.',
    searchTokens: ['msm', 'ام اس ام', 'كبريت عضوي', 'optimsm', 'تساقط شعر مزمن', 'مفاصل وغضاريف']
  },
  {
    id: 'horsetail_silica_extract',
    tradeName: 'مستخلص ذيل الحصان الغني بالسيليكا النباتية (Horsetail Extract 500mg 7% Silica - NOW / Solaray)',
    tradeNameEn: 'Horsetail Extract (Equisetum arvense) Standardized to 7% Natural Plant Silica',
    scientificName: 'مستخلص عشب ذيل الحصان المعياري بالسيليكا العضوية (Plant-Based Silica)',
    category: 'supplements',
    categoryAr: 'معدن السيليكا الأساسي لسمك خصلة الشعر ولمعانها وقوة العظام وسرعة نمو الأظافر',
    categoryIcon: '💇',
    defaultTiming: 'كبسولة واحدة بعد وجبة الغداء مع كوب ماء كبير',
    dosageForm: 'كبسولات نباتية',
    commonDoses: ['500 مجم يومياً'],
    clinicalNotes: 'توفر السيليكا العضوية القابلة للامتصاص التي تحفز خلايا الفيبروبلاست لإنتاج الكولاجين العالي الجودة، مما يزيد من سمك الشعرة الضعيفة ويعالج هشاشة الأظافر المتشققة.',
    searchTokens: ['ذيل الحصان', 'horsetail', 'سيليكا', 'silica', 'سمك الشعر', 'اظافر قوية']
  }
];
